### ISSUE TITLE
华洛芙商品属性修改类别时可修改为大类

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1009]

**Comment by wangyubest** [comment]
可以选择父级类别。
![000031](https://cloud.githubusercontent.com/assets/20236838/21882146/24991294-d8e4-11e6-92e9-4a25d665cf5c.png)

![000032](https://cloud.githubusercontent.com/assets/20236838/21882121/0505eb1e-d8e4-11e6-8efc-9a2c7421786d.png)
有公司参数：07313  商品属性修改类别时可以选择父级   0：不允许，1：允许

**Comment by feixianhui** [comment]
测试通过
