### ISSUE TITLE
新乡门店进销存

### ISSUE THREAD

**Issue by hyh199111** [kakazuo/yimengtech#1025]
需求：将本期出入中出和入分开，这样可以清楚区分。

公司参数：07312，  门店进销存是否分开   0-不允许  ， 1 - 允许

** 改前：**
![c6bt8vewa fp k p0 2j 5](https://cloud.githubusercontent.com/assets/24468189/21878799/84cbd422-d8cf-11e6-944f-1911d20a9065.jpg)
**改后：**
![qq 20170112110012](https://cloud.githubusercontent.com/assets/24468189/21878824/aeeb9d5a-d8cf-11e6-8acc-fc2e141b2d32.png)

修改过程：
1，首先设置参数，将参数保存。
2，找到js里面代表期间进出的字段。
3，修改合计里面的方法。
4，对是否需要分开出入添加判断。
5，在页面测试后没有问题，提交测试。

**Comment by feixianhui** [comment]
测试通过
