### ISSUE TITLE
新乡进销存查询数据与导出数据不对

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#1036]
客户根据种类，成色，宝石进行统计查询
结果如下。
![000033](https://cloud.githubusercontent.com/assets/20236838/21951567/4527275c-da43-11e6-95c4-bd612790896d.png)
导出结果如下
![000043](https://cloud.githubusercontent.com/assets/20236838/21951634/67e4e8e6-da44-11e6-814f-521e92a275c8.jpg)
发现导出的数据与查询的数据明显不一致。

查询时打印的参数。
![000035](https://cloud.githubusercontent.com/assets/20236838/21951579/5e40fcd6-da43-11e6-9009-0d9a95674d45.png)
可以看到这里的date2时间 尾巴有 23:59:59.
查询出的数据
![000036](https://cloud.githubusercontent.com/assets/20236838/21951587/7963ff2c-da43-11e6-844e-11f2139b4a14.png)
![000037](https://cloud.githubusercontent.com/assets/20236838/21951588/79702446-da43-11e6-9896-d4dbb40a667c.png)
期初：534
本期收入：本期进货（11410） + 本期收退货（43） = 11453
本期付出 ：本期发货（11386） + 本期退货（72） = 11458
期末 ： 期初（534） + 本期收入（11453） - 本期付出（11458） = 529
导出的数据应该是这这样才算正确。
![000040](https://cloud.githubusercontent.com/assets/20236838/21951614/e8fbc374-da43-11e6-98fe-0bbec6216707.png)
导出发现数据与所算数据一致。

造成原因：
![000042](https://cloud.githubusercontent.com/assets/20236838/21951617/0064f652-da44-11e6-9f6f-fa40c30b7e7c.png)
原来的JS页面没有在后面串上 23:59:59，导出参数不一致，查询的数据也就不一样。
这是改完之后调用导出方法所打印的参数，后面串了 23:59:59，导出数据正确。
![000039](https://cloud.githubusercontent.com/assets/20236838/21951624/15ff50e8-da44-11e6-9c3b-10f4532dc6ee.png)

**Comment by feixianhui** [comment]
测试通过
