### ISSUE TITLE
河南会员功能

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#1050]
会员公司参数：
 07317 优惠方式 3 1-活动优惠 2-会员优惠 3-同时优惠 
 07319 是否自动升vip 1 0-不允许，1-允许 
 07324 VIP享受积分优惠的起始积分 1 0-关闭，非0-优惠起始积分 
 07325 VIP优惠方式 1 0-积分抵扣，1-折扣 
 07095 销售积分 1 0-商品实际售价积分 1-实收积分

**Comment by feixianhui** [comment]
测试通过

**Comment by superman6666** [comment]
实际用时：2天
