### ISSUE TITLE
翡翠厂公司汇总查询增加供应商查询条件

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#1057]
1.与李佳沟通，需要增加一个三级公司明细的汇总，在原来的页面上选择公司的时候也要选择供应商。
2.选择公司的时候可以选择供应商，其他的供应商条件框隐藏。
3.查询，导出，打印数据都得一致。
如：
明细库存查询出来       NM0001 客户  有七件货。
![000044](https://cloud.githubusercontent.com/assets/20236838/22092131/6c6911a8-de36-11e6-847c-1ca3652b89ed.png)
去汇总查询选择条件为  老昌盛供应商时查询的数据为：
![000045](https://cloud.githubusercontent.com/assets/20236838/22092148/8804eca2-de36-11e6-968a-144d1ab61d29.png)
导出的数据为：
![000046](https://cloud.githubusercontent.com/assets/20236838/22092157/8f979a64-de36-11e6-8fb9-8e8eefc6db8e.png)
打印的数据为：
![000047](https://cloud.githubusercontent.com/assets/20236838/22092172/a307b53e-de36-11e6-95a4-c2f8bb50a763.png)
数据一一对应，即可。

**Comment by mawenhao** [comment]
测试有遗漏，后解决现场使用

**Comment by feixianhui** [comment]
测试通过
