### ISSUE TITLE
测试定价策略模块

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1077]
针对界面中所有的控件按钮等功能是否健全，界面如下
![default](https://cloud.githubusercontent.com/assets/20236933/22180226/70f6f3cc-e0a5-11e6-9b05-7ffaac6912b2.png)

**Comment by feixianhui** [comment]
#1097， #1099，#1101，#1102，#1117，#1118，#1119，#1120，#1125，#1126

**Comment by feixianhui** [comment]
实际用时：3小时
