### ISSUE TITLE
测试批发业务

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1080]
针对界面中所有的控件按钮等功能是否健全，界面如下
![1](https://cloud.githubusercontent.com/assets/20236933/22180235/aa68e3d6-e0a5-11e6-8696-e4d4cd6e4b05.png)
![2](https://cloud.githubusercontent.com/assets/20236933/22180237/af9a6e6a-e0a5-11e6-914e-e0fd4cef3c53.png)

**Comment by feixianhui** [comment]
#1107， #1108，#1109，#1110， #1111，#1124

**Comment by feixianhui** [comment]
#1124

**Comment by feixianhui** [comment]
实际用时：3小时
