### ISSUE TITLE
测试库房管理模块

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1081]
针对界面中所有的控件按钮等功能是否健全，界面如下
![default](https://cloud.githubusercontent.com/assets/20236933/22180241/c14e6d28-e0a5-11e6-99db-9b6ff6061f1b.png)

**Comment by feixianhui** [comment]
#1114， #1115， #1122，#1127，#1138

**Comment by feixianhui** [comment]
实际用时：3小时
