### ISSUE TITLE
测试零售业务模块

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1082]
针对界面中所有的控件按钮等功能是否健全，界面如下
![default](https://cloud.githubusercontent.com/assets/20236933/22180244/da1df9a4-e0a5-11e6-9828-e97f4c0bf18a.png)

**Comment by feixianhui** [comment]
#1128， #1129， #1130， #1131，#1132

**Comment by feixianhui** [comment]
实际用时：3小时
