### ISSUE TITLE
测试绩效管理模块

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1089]
针对界面中所有的控件按钮等功能是否健全，界面如下
![default](https://cloud.githubusercontent.com/assets/20236933/22180276/a1db1332-e0a6-11e6-9aad-6a13b4dda1fa.png)

**Comment by mawenhao** [comment]
https://github.com/kakazuo/yimengtech/issues/1103

**Comment by mawenhao** [comment]
工时4小时
