### ISSUE TITLE
库房管理库存查询明细成本查询

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1122]
点击刷新：
![default](https://cloud.githubusercontent.com/assets/24307572/22274179/d6cf0a5e-e2df-11e6-965d-dd78db330d96.png)
但是查询执行成功。但是合计和上面查询的数据不符。
![default](https://cloud.githubusercontent.com/assets/24307572/22274264/5c7d19d4-e2e0-11e6-8e62-abf28ae1326f.png)

导出出问题：
![default](https://cloud.githubusercontent.com/assets/24307572/22274671/ca1ea46a-e2e2-11e6-873f-b3473c795b60.png)

![default](https://cloud.githubusercontent.com/assets/24307572/22274671/ca1ea46a-e2e2-11e6-873f-b3473c795b60.png)

**Comment by hyh199111** [comment]
实际用时 2H；

**Comment by mawenhao** [comment]
测试通过
