### ISSUE TITLE
库房管理库存查询明细汇总查询

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1138]
河南点击“导出”按钮：
![default](https://cloud.githubusercontent.com/assets/24307572/22635290/3de5ef28-ec6d-11e6-83e8-869184024e08.png)

点击“打印”：
![default](https://cloud.githubusercontent.com/assets/24307572/22635306/6ea81b72-ec6d-11e6-8ab3-408e751c4d2d.png)

**Comment by mawenhao** [comment]
测试通过

**Comment by hyh199111** [comment]
实际用时 2H
