### ISSUE TITLE
初始化华洛芙老凤祥公司明牌和帝曼龙品牌数据

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#114]

**Comment by kakazuo** [comment]
@spurtAndy 请把初始化的步骤记录到这个任务里面

**Comment by spurtAndy** [comment]
初始化步骤：1、在
![qq 20160718095147](https://cloud.githubusercontent.com/assets/19886532/16904715/4d1c3528-4ccd-11e6-8c8e-cec4d64d47b7.png)页面中选择相应的公司门店品牌；
2、点击新增输入编号即可初始化当前门店和品牌的库存。
