### ISSUE TITLE
发货单撤销（替换JTK中的功能）

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1140]
由于JTK停用，需要在JSM系统中增加发货单撤销功能。
明细发货单和整包发货单都需要增加这个功能。
只对发下去还没有收的数据撤销。

**Comment by wangyubest** [comment]
1.整包发货查询功能已经完成。
![0000052](https://cloud.githubusercontent.com/assets/20236838/23002510/1d21a55a-f426-11e6-8923-e9782ee4c39e.png)
![000053](https://cloud.githubusercontent.com/assets/20236838/23002511/1d23af3a-f426-11e6-86b9-d6fc69453078.png)

**Comment by wangyubest** [comment]
实际用时：20

**Comment by feixianhui** [comment]
测试通过
