### ISSUE TITLE
输入框中增加按钮弹框可供多选

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1142]
弹出的窗口中需要可以多选，再点击确定按钮完成选择

**Comment by spurtAndy** [comment]
![qq 20170209103344](https://cloud.githubusercontent.com/assets/19886532/22766948/432addb6-eeb3-11e6-8805-a8acd300a854.png)

**Comment by spurtAndy** [comment]
选择父节点默认会自动勾选子节点
![qq 20170216091703](https://cloud.githubusercontent.com/assets/19886532/23002987/b875d484-f428-11e6-925c-99abd69ce2e3.png)

**Comment by spurtAndy** [comment]
增加多选和单选控制

**Comment by spurtAndy** [comment]
实际用时12小时

**Comment by Kim0616** [comment]
缺少可以直接输入
