### ISSUE TITLE
明细导入显示成本问题

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1144]
明细导入显示成本列是翡翠厂的需求，其他地区不需要显示，但是现在其他地区也显示：
![qq 20170208110132](https://cloud.githubusercontent.com/assets/24307572/22721824/ff03a69c-eded-11e6-8cbd-8316d6e9e5bc.png)

**Comment by wangyubest** [comment]
参数控制。
07320 明细导入页面是否显示成本 0：不需要，1：需要

**Comment by feixianhui** [comment]
测试通过
