### ISSUE TITLE
每日收银页面的合计数不能包含作废金额

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#1157]
需求：每日收银的合计数中含作废金额，明细中无作废金额，导致明细相加的总和和合计数不吻合，需要合计数中无作废金额
![qq 20170217160349](https://cloud.githubusercontent.com/assets/20296755/22965473/b5818402-f398-11e6-965c-7e7c45b959dc.png)
![qq 20170217160612](https://cloud.githubusercontent.com/assets/20296755/22965478/b9e69f32-f398-11e6-98cc-dc60901ddee7.png)

实际用时2h

**Comment by feixianhui** [comment]
测试通过
