### ISSUE TITLE
JTK条码重复检查

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#1163]

**Comment by spurtAndy** [comment]
单独制作页面，批量输入或者导入条码，在页面上显示出重复条码及其在那个库存。

**Comment by wangyubest** [comment]
![00001](https://cloud.githubusercontent.com/assets/20236838/23117943/11d0bf96-f78d-11e6-9e84-bcc5661baa21.png)
![00002](https://cloud.githubusercontent.com/assets/20236838/23117967/3a627936-f78d-11e6-936a-73309248b892.png)
有公司参数：
07322 检测条码是否启用公司筛选   0   0：不启用，1：启用

**Comment by wangyubest** [comment]
实际用时：12

**Comment by mawenhao** [comment]
测试通过
