### ISSUE TITLE
选择发货到二级库位，但一级还可以查询到商品，还可以往二级发库位，在二级公司中可以查询到相同的商品

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1175]
#1171

**Comment by hyh199111** [comment]
![default](https://cloud.githubusercontent.com/assets/24468189/23347643/acfac592-fcde-11e6-9720-c3ccea8efd5f.png)
发货前
![default](https://cloud.githubusercontent.com/assets/24468189/23347654/bcb878da-fcde-11e6-917a-3eb38816cd28.png)
二级库位接受后
![default](https://cloud.githubusercontent.com/assets/24468189/23347664/cd00ad2a-fcde-11e6-9422-5e265aec343b.png)
二级库位接受后库房明细查询，之前发的货已经没有了。

**Comment by hyh199111** [comment]
停用发库位功能。

**Comment by hyh199111** [comment]
实际用时 ：

**Comment by mawenhao** [comment]
测试通过
