### ISSUE TITLE
首饰销售查询导出不显示支付方式

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1179]
![qq 20170221164159](https://cloud.githubusercontent.com/assets/20236933/23157100/bc6f59b8-f854-11e6-8561-c983193bcd7b.jpg)
![qq 20170221164218](https://cloud.githubusercontent.com/assets/20236933/23157120/cb4d5bd8-f854-11e6-961a-4e06d80b9b7d.jpg)

**Comment by hyh199111** [comment]
![default](https://cloud.githubusercontent.com/assets/24468189/23347199/65a571d6-fcdb-11e6-95a9-d2b49e2961f3.png)

**Comment by hyh199111** [comment]
实际用时 3小时。

**Comment by mawenhao** [comment]
测试通过
