### ISSUE TITLE
客户新加的类别较多，重新生成ini文件

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#122]

**Comment by kakazuo** [comment]
@neverlosewy818 什么客户，什么类别请注明

**Comment by neverlosewy818** [comment]
华洛芙
用户新增了类别需要重新添加ini文件
文件为：
[comparison_jsm_1-1.txt](https://github.com/kakazuo/yimengtech/files/377573/comparison_jsm_1-1.txt)
路径为：D:\Tomcat6_JSM1_OFFICIAL\webapps\JSM\Lfx_Zip
