### ISSUE TITLE
库存查询明细汇总页面按照公司名称排序失败

### ISSUE THREAD

**Issue by kakazuo** [kakazuo/yimengtech#123]
之前在issue： https://github.com/kakazuo/yimengtech/issues/19 中对公司名称做过排序，经测试发现有部分数据排序没有成功，发现是代码中一部分逻辑没有修改， 另外代码本身逻辑也不完善，需要重新调整。

**Comment by kakazuo** [comment]
代码现已完成，提交review
@spurtAndy 请帮忙评审代码， 修订编号：6117

**Comment by spurtAndy** [comment]
CorpDaoImpl.java修改中多引入了import java.awt.image.CropImageFilter，调试代码没有删除。
