### ISSUE TITLE
测试-库存查询明细汇总页面按照公司名称

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#124]
需要测试公司控件中数据是否按照名称排序

**Comment by neverlosewy818** [comment]
测试结果：
点击搜索，回到一开始的注册码排序
选择一家公司，回到一开始的注册码排序
重新按照注册码排序后，该控件无法使用，关闭界面重新开启界面而然无法使用，注销重登才能使用
![qq 20160714164623](https://cloud.githubusercontent.com/assets/20236933/16833624/a97d2356-49e2-11e6-90ab-11d11cd941e7.png)
![qq 20160714164721](https://cloud.githubusercontent.com/assets/20236933/16833628/ae7044f6-49e2-11e6-988f-2914ce10d2de.png)
@kakazuo

**Comment by kakazuo** [comment]
这些bug已经修复，并合并到test branch等待测试

**Comment by kakazuo** [comment]
@neverlosewy818 请帮忙测试，谢谢
