### ISSUE TITLE
商品属性修改结算后数据的证书号，报异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1301]
![default](https://cloud.githubusercontent.com/assets/20236933/23931520/65c9984c-096d-11e7-8597-3997693b0721.png)

**Comment by spurtAndy** [comment]
@hyh199111  具体bug问下王月
bug 优先处理

**Comment by hyh199111** [comment]
实际用时：4小时

**Comment by mawenhao** [comment]
测试通过
