### ISSUE TITLE
核价功能-工费页面设置

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1303]
主要字段仓库、种类、成色、类别、宝石、经代销、超镶单粒工费、超镶粒数、成本工费、批发工费

**Comment by superman6666** [comment]
![qq 20170321190230](https://cloud.githubusercontent.com/assets/20296755/24144865/d0f316c4-0e69-11e7-98dc-088a62741339.png)

**Comment by superman6666** [comment]
实际用时16小时

**Comment by mawenhao** [comment]
测试通过
