### ISSUE TITLE
每日收入和每日营收表的预付款数据不一致

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1304]
![qq 20170315160920](https://cloud.githubusercontent.com/assets/20236933/23939043/ecf9467e-0999-11e7-8f74-c9d2b7acda09.jpg)
![qq 20170315160926](https://cloud.githubusercontent.com/assets/20236933/23939046/efbd3686-0999-11e7-9524-18cff47fb755.jpg)

**Comment by feixianhui** [comment]
![Uploading 图片.png…]()

**Comment by feixianhui** [comment]
![qq 20170323160708](https://cloud.githubusercontent.com/assets/24307572/24238077/f3e275dc-0fe3-11e7-9af3-ce2edd9b38b6.png)
![qq 20170323160728](https://cloud.githubusercontent.com/assets/24307572/24238076/f3e0c584-0fe3-11e7-9e6a-e090b92f122e.png)

**Comment by feixianhui** [comment]
实际用时：6小时

**Comment by mawenhao** [comment]
测试通过
