### ISSUE TITLE
修改树结构

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#1308]
1.添加叶子是顺序是错的（成色，类别，宝石，饰品分类，仓库）
已解决
2.分页刷新时树也会跟着只显示分页后的数据（宝石，饰品分类，仓库）
已解决
3.点击Extjs自带的排序时，点击刷新后树会不见（成色，类别，宝石，饰品分类，仓库）
禁用Extjs自带的排序

**Comment by superman6666** [comment]
实际用时10小时

**Comment by mawenhao** [comment]
测试通过
