### ISSUE TITLE
促销活动

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#1318]
旧金调换业务还是有问题
现在做的活动是新金的工艺费5折，料费是没有优惠的，旧金收旧的话，旧金收旧价格也应该不能少的。、
但是现在是工艺费优惠了，旧金收购价也会优惠。（牌价优惠）

**Comment by superman6666** [comment]
实际用时4小时

**Comment by mawenhao** [comment]
测试通过
