### ISSUE TITLE
宝石成本设置页面

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1320]
宝石重量*每克拉金额+每颗金额*宝石粒数
![qq 20170319090250](https://cloud.githubusercontent.com/assets/19886532/24077265/dd4fc482-0c82-11e7-8672-5764b7656559.png)
按宝石号、宝石大小区间，设置宝石粒成本、宝石重量成本。
增加仓库设置（非必选）

**Comment by feixianhui** [comment]
实际用时：13小时

**Comment by feixianhui** [comment]
![default](https://cloud.githubusercontent.com/assets/24307572/24482862/f6dbcd22-1526-11e7-90b8-fc1d68558804.png)

页面功能：有添加、修改、删除、审核、作废、刷新功能。

**Comment by feixianhui** [comment]
实际用时：13小时
