### ISSUE TITLE
批发料价

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1321]
按时间维护批发料价，
![qq 20170319091313](https://cloud.githubusercontent.com/assets/19886532/24077320/4e453b9e-0c84-11e7-91c3-cb548b1418b1.png)
仿照大丰这个页面的布局，复位、启用按钮去除。
增加仓库设置（非必选）

**Comment by hyh199111** [comment]
实际用时 16小时

**Comment by mawenhao** [comment]
测试通过
