### ISSUE TITLE
宝石批发价设置

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1322]
![qq 20170319090644](https://cloud.githubusercontent.com/assets/19886532/24077337/dc467cd2-0c84-11e7-9145-4e114dcd2d5e.png)
仿照大丰宝石设置页面，宝石规格换成在页面客户自己填写上下限、增加仓库设置（非必选）。按钮同工费设置页面。

**Comment by superman6666** [comment]
![qq 20170321190304](https://cloud.githubusercontent.com/assets/20296755/24144912/098d2f74-0e6a-11e7-8473-04c49093c0e1.png)

**Comment by superman6666** [comment]
实际用时14小时

**Comment by mawenhao** [comment]
测试通过
