### ISSUE TITLE
零售倍率设置

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1323]
根据仓库设置零售倍率和浮动值。

**Comment by superman6666** [comment]
![qq 20170321190349](https://cloud.githubusercontent.com/assets/20296755/24145053/89a53148-0e6a-11e7-80a8-6d3ace2536f3.png)

**Comment by superman6666** [comment]
实际用时14小时

**Comment by mawenhao** [comment]
测试通过
