### ISSUE TITLE
核价-批发价和零售价核价算法

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1349]

**Comment by spurtAndy** [comment]
实际用时14h

**Comment by spurtAndy** [comment]
成本批发工费项目，当供应商清单里的工费超过系统额定工费成本时，以清单里的工费为准，否则，以系统里的额定工费为准。举例：①PT950(女戒)，明细清单工费为140，系统成本工费为120元，导入数据参照140元。② PT950(女戒)，明细清单工费为110，系统成本工费为120元，导入数据参照120元。
当供应商清单里的工费超过系统批发工费时，以清单里的工费*1.2作为批发工费。举例：①PT950(女戒)，明细清单工费为140，系统批发工费为90元，导入数据参照140*1.2=168元。② PT950(女戒)，明细清单工费为80元，系统批发工费为90元，导入数据参照90元。

**Comment by spurtAndy** [comment]
修改 总用时 17h

**Comment by spurtAndy** [comment]
修改总用时19h

**Comment by spurtAndy** [comment]
页面副宝显示，副宝价格算入总价
修改总用时21h

**Comment by mawenhao** [comment]
测试通过
