### ISSUE TITLE
修改仓库界面

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1350]
![default](https://cloud.githubusercontent.com/assets/24307572/24482823/b110a416-1526-11e7-86a7-5f50b10e5069.png)

1、仓库编号改为仓库编码，其他档案设置依次设置。
2、仓库编码和仓库名称都不允许重复；修改：仓库编码不允许重复，仓库名称允许重复
3、仓库编码：新增仓库默认按照同级编码位数增加三位
4、仓库根目录名字叫“树”；修改：档案根目录源点统称“所有档案”，规范化。
5、仓库树形界面上，仓库名称前加仓库编码，显示直观，方便维护。
6、仓库设置缺少“停用”属性；修改：借鉴珠宝厂仓库设置，增加停用功能
7、子仓库编码为其父节点编码后加三位，新增仓库时，打印名称随仓库名称的改变而改变

**Comment by feixianhui** [comment]
实际用时：4小时

**Comment by mawenhao** [comment]
测试通过
