### ISSUE TITLE
打印退货汇总单模板

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1364]
![default](https://cloud.githubusercontent.com/assets/24307572/24483315/e2cae0cc-1529-11e7-889a-406bf168d9e8.png)

![default](https://cloud.githubusercontent.com/assets/24307572/24851856/c7e6ba24-1e07-11e7-8987-ceb388d74a55.png)

**Comment by feixianhui** [comment]
实际用时：4小时

**Comment by feixianhui** [comment]
![default](https://cloud.githubusercontent.com/assets/24307572/24851745/74e668e2-1e07-11e7-9f85-4582de08f7b1.png)
![default](https://cloud.githubusercontent.com/assets/24307572/24851826/ac456874-1e07-11e7-9baa-9d018d927150.png)

**Comment by feixianhui** [comment]
实际用时：8小时

**Comment by Kim0616** [comment]
需要修改

**Comment by feixianhui** [comment]
![default](https://cloud.githubusercontent.com/assets/24307572/24985367/387bddf8-2026-11e7-9dc5-61dae3b2e281.png)

**Comment by feixianhui** [comment]
累计用时：14小时
