### ISSUE TITLE
修改条码

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#137]
根据客户要求将系统中原有的条码修改为需要的条码

**Comment by neverlosewy818** [comment]
有条码重复，删除重复条码后，重新导入
update S_WS_STORAGEDETAIL set sd_barcode = '' where sd_barcode = ''

**Comment by kakazuo** [comment]
@neverlosewy818 请注明是那个客户，为什么出现这个问题

**Comment by neverlosewy818** [comment]
新乡，入库时客户自定义编的条码，现在需要修改为符合规定的条码。
我试用update直接在数据库上将系统中原有的条码修改为需要的条码。
update的过程中，出现要修改的条码与系统中已有的条码重复的情况。
我再将重复的条码查出，反馈给客户，修改条码之后重新进行update。

**Comment by kakazuo** [comment]
good！！！
