### ISSUE TITLE
款式界面设置

### ISSUE THREAD

**Issue by feixianhui** [kakazuo/yimengtech#1374]
![default](https://cloud.githubusercontent.com/assets/24307572/24532415/dab09ade-15f2-11e7-9623-7b2fae934fc9.png)

款式界面功能：
1、根据类别新增款式，在同一个品牌同一类别下款式款号和名称不能相同。
2、修改款式时，在同一个品牌同一类别下款式款号和名称不能相同。
3、删除功能
4、停用功能

**Comment by feixianhui** [comment]
实际用时：8小时

**Comment by mawenhao** [comment]
测试通过
