### ISSUE TITLE
河南销售单品名显示问题

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#1392]
完成时间3月31日下午五点之前
![default](https://cloud.githubusercontent.com/assets/20236933/24538403/8e2487ba-161b-11e7-814e-7b701b1713c5.jpg)

**Comment by spurtAndy** [comment]
如果销售第一件是硬金后面销售是黄金打印出来的单子会全是硬金。反之第一件是黄金打出来都是黄金。
