### ISSUE TITLE
仓库页面修改

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1396]
完成时间 4月1日
1、仓库编码应该为自动累计加1
2、仓库左边属性结构，右边只显示当前选中仓库参数。点击树节点显示当前选中的记录
3、需要有启用按钮。

**Comment by feixianhui** [comment]
![default](https://cloud.githubusercontent.com/assets/24307572/24545497/f193a42a-1639-11e7-82fc-71abc8eb60b3.png)
![default](https://cloud.githubusercontent.com/assets/24307572/24545534/0fb6fcf4-163a-11e7-8100-361608127119.png)

**Comment by feixianhui** [comment]
实际用时：3小时

**Comment by mawenhao** [comment]
测试通过
