### ISSUE TITLE
宝石成本页面修改

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1398]
完成时间 4月5日
1、宝石成本价页面，仓库控件隐藏。
2、审核后如果新增宝石成本和原来在用的宝石设置重复，则将原来宝石成本作废，在用新的宝石成本。

**Comment by feixianhui** [comment]
新增宝石成本时根据参数宝石成本重量区间作为宝石成本的重量上限和重量下限。
![default](https://cloud.githubusercontent.com/assets/24307572/24538008/1a161066-1619-11e7-9280-8365d3f213bf.png)
![default](https://cloud.githubusercontent.com/assets/24307572/24540805/5bf52252-1627-11e7-842d-a3f630206536.png)
![default](https://cloud.githubusercontent.com/assets/24307572/24540815/684a0e64-1627-11e7-8f3b-032c774d8658.png)

**Comment by feixianhui** [comment]
实际用时：4小时

**Comment by mawenhao** [comment]
测试通过
