### ISSUE TITLE
以及明细进货页面，库存明细汇总页面，新增退货明细打印测试

### ISSUE THREAD

**Issue by kakazuo** [kakazuo/yimengtech#140]
@superman6666 请帮忙测试下面功能，谢谢
1级明细进货页面增加各项成本字段 https://github.com/kakazuo/yimengtech/issues/28
库存明细汇总页面增加底部合计栏 https://github.com/kakazuo/yimengtech/issues/65
新增退货明细打印单据 https://github.com/kakazuo/yimengtech/issues/18

**Comment by superman6666** [comment]
经测试，无问题。@kakazuo,可以与trunk分支合并

**Comment by kakazuo** [comment]
cool
