### ISSUE TITLE
系统中经代销修改

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1402]
4月5日完成
1、供应商无需经代销选择项，编号自动获取，不允许修改。供应商页面中经代销属性去掉。
2、在仓库页面增加经代销选项，给仓库绑定经代销属性。
3.仓库不可以重复
4.优化之前的修改方法的代码

**Comment by superman6666** [comment]
实际用时8小时

**Comment by mawenhao** [comment]
测试通过
