### ISSUE TITLE
宝石批发价页面导入

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1404]
完成时间 4月6日
1.核价业务中宝石批发价页面增加导入功能
2.按仓库，宝石，石重区间，颜色，净度，切工排序
3.点击品牌，仓库，宝石，石重区间，颜色，净度，切工按钮自动查询
4.品牌，仓库，宝石，石重区间，颜色，净度，切工按钮第一行增加空白行
5.宝石批发价页面修改列显示问题
6.在镶嵌厂系统中增加参数及宝石区间
7.给镶嵌厂导入宝石批发价
8.修改宝石规格控件的排序
9.修改参数页面获取明细数据的排序

**Comment by superman6666** [comment]
实际用时16小时

**Comment by mawenhao** [comment]
发现问题1：由于电脑分辨率原因，导致切工选项无法显示全

**Comment by mawenhao** [comment]
测试通过
