### ISSUE TITLE
JTK功能沟通

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#1407]
完成时间 4月5日
1、JTK功能是否有
2、JTK功能能否正常使用

**Comment by neverlosewy818** [comment]
沟通结果，客户不承认得知JTK功能已存在于测试库，最终商讨于4月5号给他们系统部演示JTK功能

**Comment by neverlosewy818** [comment]
与客户沟通演示了功能，重复条码检测导出来无数据，其余功能可能还会有新的需求更改
