### ISSUE TITLE
明细库存查询选择非库位查询抛异常

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#151]
导致此bug的主要原因是hql的查询语句在成本价为空的时候少了一个右括号
解决方法是：在成本价为空的时候给他加上一个右括号
![qq 20160718132510](https://cloud.githubusercontent.com/assets/20296755/16906524/ce2350e8-4ceb-11e6-832e-8e91fe94c5dd.png)

bug已解决，code已提交， @kakazuo 请检查

**Comment by kakazuo** [comment]
@superman6666 thanks,  I will review ASAP

**Comment by kakazuo** [comment]
done
