### ISSUE TITLE
首饰销售明细增加可一次性查阅并导出等一系列功能测试

### ISSUE THREAD

**Issue by kakazuo** [kakazuo/yimengtech#153]
以下功能需要进行测试：
1 首饰销售明细增加可一次性查阅并导出公司整体数据的功能，此类功能中将需要加入部分字段   https://github.com/kakazuo/yimengtech/issues/97
2 增加可一次性查询并导出品牌所有门店柜组进销存数据的功能  https://github.com/kakazuo/yimengtech/issues/103
3 柜组进销存需体现上下柜的数据 https://github.com/kakazuo/yimengtech/issues/143
4 发布补货计划时出现不可发布的现象  https://github.com/kakazuo/yimengtech/issues/142
5 门店调拨调拨后grid中数据不清除   https://github.com/kakazuo/yimengtech/issues/136
6 大丰不能计算补货 https://github.com/kakazuo/yimengtech/issues/141 
7 选择发货可以批量添加不是本库存的货 https://github.com/kakazuo/yimengtech/issues/118
8 库位发货记录到过程  https://github.com/kakazuo/yimengtech/issues/91

**Comment by superman6666** [comment]
经测试，无问题。@kakazuo,可以与trunk分支合并

**Comment by kakazuo** [comment]
@superman6666 thanks so much!
