### ISSUE TITLE
二级库房接收明细退货需要按照专卖店进行区分后操作

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#162]
二级库房接收明细退货页面需要可以按照门店筛选

**Comment by wangyubest** [comment]
批发业务-->收货-->收退货-->接收明细退货     登录一个2级账号，可以根据门店来进行数据的筛选。
![fed m7 l1fqd w63_w2rnbc](https://cloud.githubusercontent.com/assets/20236838/16939486/b660ff22-4db4-11e6-89dc-0430f0dc8670.jpg)  @kakazuo

**Comment by kakazuo** [comment]
![qq 20160722094259](https://cloud.githubusercontent.com/assets/5010445/17044222/b979a2b6-4ff0-11e6-8ddd-5e428b8ee97a.png)

图示的地方需要修改
