### ISSUE TITLE
系统中增加老凤祥二码

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#163]
系统中增加老凤祥二码：需要二码导入后，在系统中一直跟随饰品，不得消失。

**Comment by spurtAndy** [comment]
检测条码和查询码

**Comment by superman6666** [comment]
这次改动主要是在StorageDetail表中加入了两个字段 分别是检测条码和查询码 并且做了品牌控制 只有老凤祥才能把导入的二码写到表中
功能已做好 code已提交  @kakazuo 请检查
