### ISSUE TITLE
商品跟踪输入条码查询报错

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#164]
大丰 老庙品牌 
![140959211938052342](https://cloud.githubusercontent.com/assets/19886532/16910064/f41ae8e8-4d08-11e6-9a88-bd3d030c5073.jpg)
112410709188

**Comment by wangyubest** [comment]
经测试发现：条码报错问题，是因为后台并没有走近赋值为-1的一个方法，现已解决。
                     证书号找不到货物问题，是因为用户在导入货物文件的时候，证书号这个字段，最后可能会有空格字符，现以在后台自动去掉空格字符。

**Comment by wangyubest** [comment]
@kakazuo

**Comment by kakazuo** [comment]
![qq 20160722095307](https://cloud.githubusercontent.com/assets/5010445/17044383/2f8429ee-4ff2-11e6-9071-78f5dd2442b1.png)

请去除字符串判空逻辑
