### ISSUE TITLE
旧品上缴单和上级旧品接收单制作

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#288]
[单据打印模板.xlsx](https://github.com/kakazuo/yimengtech/files/408010/default.xlsx)

门店旧品上缴中增加上缴单，模板参考文件中的三级模板
一级 二级增加接收单，模板参考文件中的一级模板。

**Comment by spurtAndy** [comment]
OM/oldmaterialPaid.js，receiveOld.js

**Comment by wangyubest** [comment]
已完成。 @kakazuo

**Comment by kakazuo** [comment]
请查看测试结果

**Comment by wangyubest** [comment]
位置已调整。 请测试 @neverlosewy818 
![1](https://cloud.githubusercontent.com/assets/20236838/17958823/265539d8-6acf-11e6-8b7b-94dc9f8bd323.png)
![2](https://cloud.githubusercontent.com/assets/20236838/17958827/2ce96c88-6acf-11e6-8364-2a82b718a770.png)
