### ISSUE TITLE
设计及草写新项目流程图

### ISSUE THREAD

**Issue by Kim0616** [kakazuo/yimengtech#294]
设计及草写新项目流程图

**Comment by Kim0616** [comment]
![1](https://cloud.githubusercontent.com/assets/20238904/17545976/6a380432-5f12-11e6-9201-6685f3e17c0a.png)
![Uploading 2.png…]()
![Uploading 3.png…]()

**Comment by kakazuo** [comment]
@Kim0616 你还有张图片没有上传上来

**Comment by Kim0616** [comment]
![2](https://cloud.githubusercontent.com/assets/20238904/17546117/22dd1d06-5f13-11e6-8e3c-41b76700107f.png)

**Comment by Kim0616** [comment]
![3](https://cloud.githubusercontent.com/assets/20238904/17546121/2bfc353e-5f13-11e6-8fba-2a9bde3388e6.png)

**Comment by Kim0616** [comment]
今天和邱老师沟通 
客户-仓库-库位-门店的概念 没有明确区分

**Comment by Kim0616** [comment]
![Uploading 4.png…]()

**Comment by spurtAndy** [comment]
![5](https://cloud.githubusercontent.com/assets/19886532/17576343/37331918-5fa4-11e6-9ec2-671c7c8e31e8.png)

**Comment by Kim0616** [comment]
![6](https://cloud.githubusercontent.com/assets/20238904/17577213/9e974936-5fad-11e6-8dc2-b70e013336ad.png)

**Comment by Kim0616** [comment]
最后一张图片  基本可以理清楚 客户-仓库-库位-及功能模块的关系图
