### ISSUE TITLE
跟数据库交互会出现数据不全或者数据错乱的问题

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#302]
河南分称入库时，网络卡顿或者用户重复点击提交，导致明细入库数据显示重复三遍 
跟数据库交互会出现数据不全或者数据错乱的问题

![qq 20160808160322](https://cloud.githubusercontent.com/assets/20236933/17544715/817fbb50-5f0b-11e6-8f6d-48f9bbe2a494.png)

**Comment by neverlosewy818** [comment]
这问题导致的同样问题https://github.com/kakazuo/yimengtech/issues/301

**Comment by spurtAndy** [comment]
目前那个bug还不能重现，我做了这个页面的代码调整。
function confirmSeparateDetailA() {
            Ext.MessageBox.confirm('提示','请核对分秤明细数据，您确定入库吗？',function(btnId){
                if(btnId == 'yes') {
                    Ext.MessageBox.confirm('提示','入库后不能再修改数据，请再次确定入库并打印入库单，继续？',function(btn){
                        if(btn == 'yes') {
                            var msgTip = MY.util.showWaitMsg('正在提交数据，请稍候...');
                            function callBack(result) {
                                if(!Ext.isEmpty(result)){
                                    DWREngine.setAsync(false);                                        //临时设置同步
                                    detailPrintStore.load({params:{start:0,limit:999999,coId:_userCorp[0],brId:_brId,sbgId:_sbgId,sbgState:2}});
                                    DWREngine.setAsync(true);                                         //恢复默认异步  

```
                                _group.set('sbg_state',2);
                                detailStore.load({params:{start:0,limit:detailPageBar.pageSize,coId:_userCorp[0],brId:_brId,sbgId:_sbgId,sbgState:_group.get('sbg_state')}
                                    ,callback:function(){
                                        msgTip.hide();
                                        myPrintWin.show();
                                        myPrintWin.setTitle('单据打印');
                                        var temp1 = result.split(",");
                                        myPrintWin.dateTime = temp1[1];
                                        myPrintWin.jkdh = temp1[0];
                                        myPrintWin.myForm.getForm().reset();
                                        groupStore.reload();
                                    }});
                            }else{
                                msgTip.hide();
                            }                               
                        }   

                        dwrWs.confirmSeparateDetail(_sbgId,_userCorp[0],_brId,_user_en,_user_ch,{callback:callBack,errorHandler:MY.util.dwrCallError});
                    }   
                }); 
            }   
        }); 
    }   
```

这个方法中我使得遮罩在全部执行完了之后再消失。
