### ISSUE TITLE
与老凤祥信息部沟通流程图及系列问题

### ISSUE THREAD

**Issue by Kim0616** [kakazuo/yimengtech#311]
1 老凤祥是以什么价格发下去  是批发价 还是零售价  成本价如果定。
2.定价 什么时候跨级定价格。
3.批发价 零售价 的管理
4.如何分层级
5.每家厂的数据及系统 是否独立
6.库位销售模式及统计
7.客户与库位 有没有交叉

需要进一步了解:
1.镶嵌厂进货方式,几个部门,如何管理
2.其他厂进货方式,如翡翠厂
3.客户数量、分类，除自营门店外，还有什么特殊情况
4。创库管理，库位划分、库位管理（专人？）等
5。各厂是否独立软件运行？
6。发货文件细节，格式、压缩否等
7。财务需求
8、即使各厂独立软件，但基础数据，如成色、宝石、类别、品名等，以及客户名录最好完全一致，甚至只有一份，为将来老凤祥完整信息化打下基础

**Comment by spurtAndy** [comment]
![qq 20160818190559](https://cloud.githubusercontent.com/assets/19886532/17771661/d1bd30d6-6576-11e6-9f6e-28872116e90b.png)
