### ISSUE TITLE
FineReport研究

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#337]
1、调用FineReport列表
2、中文名称编码问题

**Comment by kakazuo** [comment]
Finereport 相关资料：
http://www.finereport.com/
http://help.finereport.com/

API:
http://help.finereport.com/category-view-169.html

调研方向： finereport json 插件
插件开发教程： http://www.finedevelop.com/pages/viewpage.action?pageId=360511

url传递参数，例如：
/WebReport/ReportServer?reportlet=Gettingstarted.cpt&地区=华东"

url中包含中文没有问题， 例如：
http://137.1.1.6:8075/WebReport/ReportServer?reportlet=你好.cpt

FR前端api
http://www.cnblogs.com/laoA188/p/5287084.html

接下来工作：
尝试把JSM的权限控制和Fr的权限控制整合到一起（URL嵌入， 直接拷贝Webroot）

**Comment by kakazuo** [comment]
报表adapter设计
![qq 20160830093411](https://cloud.githubusercontent.com/assets/5010445/18072971/fc98e8dc-6e94-11e6-8bfb-5b46c70d553d.png)
