### ISSUE TITLE
设计一个页面  计算周转率（计算公式：件数周转=分店现存件数/分店近一个月销售件数）

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#342]
1.周转计算：计算所有店铺近一个月件数周转情况，此数据将作为货品分配的优先依据，周转越小优先级别越高
计算公式：件数周转=分店现存件数/分店近一个月销售件数。（现存为时间为计算当日时间，近一个月时间为计算当日向前推算31天）
周转分类:依据品牌、种类、成色、宝石分类，具体分类参见周转分类表

首先设计表,然后在hbm里创建表，写实体类，vo，dao等等。
然后去画页面
![qq 20160820152015](https://cloud.githubusercontent.com/assets/20296755/17829702/ad4da0fe-66e9-11e6-901d-ed59875c9b7c.png)

再去写后台做功能，功能包括（新增，修改，复位，删除，计算周转率，查询当前，查询全部（历史））
![qq 20160820152148](https://cloud.githubusercontent.com/assets/20296755/17829711/ef3b8d46-66e9-11e6-8b2b-80c08c4bf418.png)
![qq 20160820152212](https://cloud.githubusercontent.com/assets/20296755/17829714/0696e468-66ea-11e6-83ca-6dcec7b15db4.png)

功能已做好，code已提交 @kakazuo

**Comment by kakazuo** [comment]
添加一下任务的描述

发自我的 iPhone
