### ISSUE TITLE
选择发货二级发库位

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#346]
一级选择发货时，选择发库位，选择供应商选择库位，虽然报错，但是数据也发过去了
![qq 20160817200750](https://cloud.githubusercontent.com/assets/20236933/17735702/50019e1c-64b6-11e6-8855-1e7497787570.png)

一级选择发货时，选择发库位，只选择库位，报错数据发不过去
![qq 20160817201054](https://cloud.githubusercontent.com/assets/20236933/17735781/c4779288-64b6-11e6-9a61-7e9b5b1b871e.png)

**Comment by hyh199111** [comment]
实际用时：2.5小时
