### ISSUE TITLE
山东加密狗登陆异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#350]
![qq 20160817113424](https://cloud.githubusercontent.com/assets/20236933/17723731/fdf97afa-646e-11e6-82bd-8578d4c08b22.png)
查下来狗没过期，让客户排除是电脑的问题还是狗的问题

**Comment by kakazuo** [comment]
跟进下状态

**Comment by neverlosewy818** [comment]
沟通后得知，客户后来使用正常，属于客户操作问题
