### ISSUE TITLE
河南查询数据（查库存、商品跟踪）比之前慢

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#355]
2016-08-16更新后查询速度慢，

**Comment by neverlosewy818** [comment]
调查结果：
直接连河南正式库，操作下来感觉明显比之前发现问题时速度快得多，可能与网络的因素有关，查数据查库存这些基本比较正常，商品跟踪依旧缓慢，查出数据一般需要1分钟左右

**Comment by kakazuo** [comment]
验证是不是硬盘读取速度问题导致

**Comment by neverlosewy818** [comment]
经验证
1、商品跟踪代码存在bug，查询速度过慢，代码需要优化
2、查询时没有提醒，需要优化
