### ISSUE TITLE
现金管理字段修改

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#365]
今日结余金额改成今日累计金额
![qq 20160818185418](https://cloud.githubusercontent.com/assets/19886532/17771378/3202138c-6575-11e6-847b-2405bf043a2e.jpg)

**Comment by spurtAndy** [comment]
![qq 20160818185806](https://cloud.githubusercontent.com/assets/19886532/17771479/bf505bc2-6575-11e6-9c9c-8f3d2ef60437.png)

**Comment by kakazuo** [comment]
@neverlosewy818  请测试
