### ISSUE TITLE
回仓货品重新分配

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#374]
分配规则: 根据门店近一个月销售明细与回仓货品明细做数据匹配，主要参考维度为：店铺名称、周转排名、类别、克重段  
该步骤主要为分配提供件数依据，计算结果能够一次性导出系统，便于核对结果以及为发货提供依据                                    

主要了解明确的需求，和张伟讨论怎么去设计，在讨论中发现很多疑问，然后与李浩进行详细的沟通解决疑问，此次沟通为以下3个点：
1.在周转率很多为空的时候该怎么对其排序。李浩明确为随机排序
2.是否需要克重区间明细件数和明细数据。李浩明确为需要明细件数
3.每个类别是否需要一个克重区间。

**Comment by kakazuo** [comment]
1. 设计克重区间表
2. 提供管理这个克重区间表格的页面及后台实现
3. 获取周转率并按照周转率字段从小到大排名（对于周转率为空的记录放到最后）
4. 设计补货件数表，实现对这张表的基本crud操作
5. 针对周转率排名计算各个克重区间的补货件数， 并保存到上述补货件数表

**Comment by superman6666** [comment]
讨论好需求后设计补货结果表，然后设计页面并实现后台。
设计的表如下，并在Java里实现代码：
![qq 20160823232842](https://cloud.githubusercontent.com/assets/20296755/17898186/6290b414-6989-11e6-9eda-21a8c199d0bf.png)
设计页面如下：
![qq 20160823233209](https://cloud.githubusercontent.com/assets/20296755/17898306/def61364-6989-11e6-83d1-3ef1ec1288a4.png)
接来下实现页面的功能
1.首先在后台根据周转率给同一品牌，公司，种类，成色，宝石，类别下的门店进行排序
2.查询同一品牌，公司，种类，成色，宝石，类别下的克重区间
3.检查此批次号是否在商品分配表是否存在，如果存在则不分配，不存在则分配
4.查询同一品牌，公司，门店，种类，成色，宝石，类别，销售时间下的每个克重区间的销售件数
5.根据批次号查询同一品牌，公司，种类，成色，宝石，类别下的每个克重区间的回仓件数
6.修改分配过的明细状态,把每条明细写入商品分配表中
功能已做好，code已提交， @neverlosewy818 请测试
