### ISSUE TITLE
测试设计一个页面 计算周转率（计算公式：件数周转=分店现存件数/分店近一个月销售件数）

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#375]
https://github.com/kakazuo/yimengtech/issues/342

**Comment by neverlosewy818** [comment]
种类没选报异常
![qq 20160824114443](https://cloud.githubusercontent.com/assets/20236933/17843204/dd44a6ac-685d-11e6-9c1b-74f64cf67205.png)

**Comment by neverlosewy818** [comment]
库存数量不对
![qq 20160824114348](https://cloud.githubusercontent.com/assets/20236933/17843211/f226b9b6-685d-11e6-9ca7-63aeb0309aa9.png)
![qq 20160824114330](https://cloud.githubusercontent.com/assets/20236933/17843235/2bd99a84-685e-11e6-84e6-045c2600393e.png)

**Comment by kakazuo** [comment]
做假数据验证销售件数是否正确

**Comment by neverlosewy818** [comment]
数据没问题，<修改>功能有问题
![qq 20160824162246](https://cloud.githubusercontent.com/assets/20236933/17991266/a2ac79f6-6b6f-11e6-8257-a2123302b2ab.png)

**Comment by neverlosewy818** [comment]
提交后，输入金额的地方最好做下清空，避免反复点击反复添加

**Comment by neverlosewy818** [comment]
没有选择数据，点击计算先弹出选择计算日期后弹出请选择要计算的周转率规则，有数据时，没选择要计算的数据，也出现同样的情况。建议点击计算后先判断是否有选择再弹出计算日期
![qq 20160827061052](https://cloud.githubusercontent.com/assets/20236933/18021882/0ad97c2e-6c1d-11e6-8013-cd7f424fcc4c.png)
改好了

**Comment by neverlosewy818** [comment]
选择品牌第一个空格，会弹出提示要选择品牌，建议把空格直接去掉
![qq 20160827061425](https://cloud.githubusercontent.com/assets/20236933/18021973/c62d5dba-6c1d-11e6-9feb-dcd974e0a5f5.png)
改好了
![qq 20160827061439](https://cloud.githubusercontent.com/assets/20236933/18021969/bfcbfaee-6c1d-11e6-9c7a-fc76cef3f636.png)

**Comment by neverlosewy818** [comment]
日期范围建议去掉，没什么意义，反而会给用户一种误解，要么改成点击一条数据，显示那条数据的在用计算时间
![qq 20160827062640](https://cloud.githubusercontent.com/assets/20236933/18022179/53f5096c-6c1f-11e6-92b8-0df209de5b72.png)
为必要该 在设计时跟张伟讨论过 有必要显示 可以去问张伟

**Comment by neverlosewy818** [comment]
双击修改后无法保存
![qq 20160827063220](https://cloud.githubusercontent.com/assets/20236933/18022282/11f86602-6c20-11e6-863b-b64fb7504a97.png)
没发现双击不能修改  我这边正常
