### ISSUE TITLE
商品属性修改bug

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#391]
![qq 20160825162731](https://cloud.githubusercontent.com/assets/19886532/17962881/82407562-6ae5-11e6-92e8-fa7022b72178.png)
![qq 20160825165705](https://cloud.githubusercontent.com/assets/19886532/17962886/84f894ba-6ae5-11e6-8b5b-b545ffee0415.png)
输入一个条码出来两条记录，并且修改时报异常。

**Comment by superman6666** [comment]
问题：当进一件货的时候 再把这件货退出系统 这件货会生成一个时间搓的条码 当再进一件同条码的商品时，去商品属性修改页面用条码查询的时候会出现两个相同条码的商品 （一个是退货的，一个是进货的）但其中有一个条码是带时间搓的（退货的）。现在就是要修改成只查询进货的商品，不需要查询退货的（带时间搓的）
解决方法：由于这个页面的条码查询跟商品跟踪页面的条码查询用的是同一个方法，而这个方法用了模糊查询，所以能查出多个条码，但是商品属性修改页面不需要查询出退货的数据（带时间搓的），最后重新写了一个不用模糊查询的方法。
功能已做好，请测试！

**Comment by mawenhao** [comment]
测试通过
