### ISSUE TITLE
明细发货、退货查询页面bug

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#393]
批发业务--查询--退货查询
批发业务--查询--发货查询

查询条件缺少判断，什么都不选点击查询不弹提示
查询时缺少遮罩

![qq 20160825183449](https://cloud.githubusercontent.com/assets/20236933/17966215/046b1652-6af3-11e6-898d-9d90097f85df.png)
![default](https://cloud.githubusercontent.com/assets/24468189/23146799/fa466f5a-f814-11e6-8d6c-56bfa3ab5792.png)

![default](https://cloud.githubusercontent.com/assets/24468189/23146804/08c110e4-f815-11e6-84cc-d85f66dff04e.png)

**Comment by hyh199111** [comment]
实际用时：1.5小时

**Comment by mawenhao** [comment]
测试通过
