### ISSUE TITLE
华洛芙营收表，需要增加全公司全门店 导出

### ISSUE THREAD

**Issue by Kim0616** [kakazuo/yimengtech#404]
华洛芙营收表，需要增加全公司全门店 导出

**Comment by Kim0616** [comment]
新增导出2按钮

导出后，营收表增加 公司 门店2个字段

**Comment by Kim0616** [comment]
![qq 20160829170004](https://cloud.githubusercontent.com/assets/20238904/18046354/100a957c-6e0a-11e6-8fd3-6dd8116c95af.png)

**Comment by superman6666** [comment]
在不选公司，门店的情况下直接导出所有公司，所有门店的数据
![qq 20160831155722](https://cloud.githubusercontent.com/assets/20296755/18120766/c7378a40-6f93-11e6-9dd7-929f9500cf01.png)
功能已做好，code已提交， @neverlosewy818 请测试
