### ISSUE TITLE
门店进销存修改

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#407]
大丰数据库
1、门店进销存在途数据增加合计。
2、门店进销存数据中素金金额需要显示为零。

![791052628933605070](https://cloud.githubusercontent.com/assets/19886532/18038326/2907c702-6dc9-11e6-8484-7d3c4fe821d9.jpg)

**Comment by wangyubest** [comment]
已完成修改 。效果如下：
![001](https://cloud.githubusercontent.com/assets/20236838/18119067/52db701a-6f8b-11e6-9f98-43b6d600043b.png)
![002](https://cloud.githubusercontent.com/assets/20236838/18119068/52e0f0a8-6f8b-11e6-88c0-f8e20ce555f3.png)
