### ISSUE TITLE
重定价后打印模板错误

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#418]
1.山东重定价有问题    没有合计金额
2.批发价改成240以后再补打单据批发价还是234
![qq 20160830133818](https://cloud.githubusercontent.com/assets/20236933/18077268/099ddaac-6eb7-11e6-94be-ed19553610cf.png)

**Comment by superman6666** [comment]
1.这个单子的合计金额已经修改好，但是重定价页面也发生这个问题，所以跟着一起也修改了
2.这个问题是给他们开放了新的页面
![qq 20160906113444](https://cloud.githubusercontent.com/assets/20296755/18261035/f22cef56-7425-11e6-9a5e-e6a717a6a285.png)
两个问题都已经解决，然后就是手把手叫山东客户怎么使用这个页面。
1）.等待王月测试时再提交代码 
2）.王月说他要测试
3）.我提交代码
4）.测试通过
