### ISSUE TITLE
旧品进销存收旧换新数据重复

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#422]
门店在上缴旧金之后，顾客退货、换款。实际旧料已经上缴库房，但门店在换新销售时，仍需要将之前收到的旧料抵扣入新换的货品价格中。此操作会导致旧品上缴页面重复录入了该旧料，同时进销存报表也重复显示该旧料，导致系统数据与实际数据不符（bug）

**Comment by spurtAndy** [comment]
王宇已验证这个bug是存在的

**Comment by spurtAndy** [comment]
解决方案：对于已上缴商品增加在旧品的退货process。结余数据=当前门店旧品库存-退货数据。
![qq 20160901091240](https://cloud.githubusercontent.com/assets/19886532/18152130/3acff55e-7026-11e6-8809-af2df31db0d9.png)

**Comment by spurtAndy** [comment]
代码已提交 
![qq 20160901102007](https://cloud.githubusercontent.com/assets/19886532/18153089/b31ca596-702d-11e6-9901-87d556a8d44b.png)
