### ISSUE TITLE
测试补货中取门店补货数量修改

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#426]
https://github.com/kakazuo/yimengtech/issues/399

**Comment by neverlosewy818** [comment]
测试结果：
1、门店实际补货数量要是为0，库存数量或者门店在库库存数量要是有值，门店实际补货数量就会为负数
![qq 20160902172503](https://cloud.githubusercontent.com/assets/20236933/18199424/c97b62cc-7132-11e6-8bcc-549cedf214f4.png)

2、点击计算补货数量是报错
![qq 20160902172450](https://cloud.githubusercontent.com/assets/20236933/18199402/aaf3ccae-7132-11e6-9a5d-55625c158dcd.png)
![qq 20160902172753](https://cloud.githubusercontent.com/assets/20236933/18199454/eba13fa2-7132-11e6-80f7-74ccc1d1cbd0.png)

3、输入批次号的时候没有 进行判断批次号是否存在，在输入错误批次号的情况下没有提示批次号错误
![qq 20160908190833](https://cloud.githubusercontent.com/assets/20236933/18347411/e86e9c3e-75f7-11e6-9cdc-2ae6ea76fa49.png)

4、计算数量完成后没有提示完成

**Comment by spurtAndy** [comment]
两个bug，已提交Code，请测试。
