### ISSUE TITLE
搭建测试环境

### ISSUE THREAD

**Issue by mawenhao** [kakazuo/yimengtech#432]
创建数据库实例并导入相关数据，部署除了河南及华洛芙外的五个测试环境（大丰，山东，翡翠场，重庆，新乡）
大丰库表实例，表空间已建好

**Comment by kakazuo** [comment]
1. 创建表空间 -- 已完成
2. 导数据

**Comment by mawenhao** [comment]
9月1日完成内容概述：
安装新乡，大丰，山东，重庆 ，翡翠场的TOMCAT，给与不同的端口号并且记录
导入除新乡外，其余四个地方的相关数据
