### ISSUE TITLE
明细库存查询导出异常

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#435]
明细库存查询的数据导不出来
![837797500750385192](https://cloud.githubusercontent.com/assets/19886532/18152252/1ad96a4a-7027-11e6-9c3e-85055363b3c8.png)

**Comment by spurtAndy** [comment]
导出非库位的数据时异常

**Comment by superman6666** [comment]
主要原因是导非库位数据时的sql缺少右括号
![qq 20160901105918](https://cloud.githubusercontent.com/assets/20296755/18153932/31181ade-7033-11e6-8562-3f47d57fdee3.png)
bug已解决，code已提交， @neverlosewy818 请测试
