### ISSUE TITLE
测试柜组进销存收入金额与首饰销售功能所查收入数据不一致 

### ISSUE THREAD

**Issue by kakazuo** [kakazuo/yimengtech#438]
请参考 #420 
测试方法：做多笔销售，收银时使用不同舍位选项， 最后比较销售查询中的实际收入合计与销售明细查询中的实际收入合计是否一致

**Comment by neverlosewy818** [comment]
测试结果：
销售多笔单件商品的单子，销售查询中的实际收入合计与销售明细查询中的实际收入合计一致
销售一笔多件商品的单子，销售查询中的实际收入合计与销售明细查询中的实际收入合计一致
销售计奖、绩效无影响
