### ISSUE TITLE
接收明细退货时异常

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#445]
![220430729536406368](https://cloud.githubusercontent.com/assets/19886532/18161858/5923605a-7066-11e6-8bb3-719d9f64a8a3.jpg)

**Comment by superman6666** [comment]
原因是清缓存的问题
![qq 20160905133957](https://cloud.githubusercontent.com/assets/20296755/18238304/49fc5e46-736e-11e6-8e5e-4c29b65c95f2.png)
注释之后就能正常退货
问题已经解决，待王月测试时再提交code @neverlosewy818 请测试
