### ISSUE TITLE
河南调价后价格不对

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#451]
河南以前没调价的时候是红框里面的价格
结果调价以后以前的价格还在
![494c3c48-6eb7-11e6-8b37-a31e84243abb](https://cloud.githubusercontent.com/assets/20236933/18193639/2e6752c0-7112-11e6-917d-f014586c1413.jpg)

**Comment by wangyubest** [comment]
经与韩松超沟通，K金按  元/件 销售显示价格。效果图如下：
![040](https://cloud.githubusercontent.com/assets/20236838/18263683/87368162-743e-11e6-87db-9e4ec86c0afa.png)
提交了两个页面：
RA:    queryJewelSales
          jewelrySell
原文件已备份，现测试人员对7个地方进行测试。
