### ISSUE TITLE
成本汇总查询页面选择全部选项时数据不对

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#454]
选择全部时出来的数据减去一级公司的库存才和整个公司数据相等。
![421114066499896229](https://cloud.githubusercontent.com/assets/19886532/18235127/82dfd690-7349-11e6-9aa1-e0d2fe09acca.jpg)
![96674859674774781](https://cloud.githubusercontent.com/assets/19886532/18235128/82e17ce8-7349-11e6-9144-0fef7f98e807.jpg)

**Comment by kakazuo** [comment]
打电话确认

**Comment by spurtAndy** [comment]
和客户沟通，然后远程演示，但是我这边测试下来没有问题。客户会继续测试。

**Comment by spurtAndy** [comment]
因为客户很多错误数据没有退出系统后导致数据和实际不符。客户现已将无用数据退出系统，数据核对正确。
