### ISSUE TITLE
每日营业收入统计表中其他2修改为“免工费金额”

### ISSUE THREAD

**Issue by kakazuo** [kakazuo/yimengtech#458]
大丰需要将每日营业收入统计表中其他修改为免工费金额，且不能影响其他地方使用，解决方法（采用参数控制）
![009](https://cloud.githubusercontent.com/assets/20236838/18235864/93404408-7352-11e6-93d3-f9df8fe19096.png)

**Comment by wangyubest** [comment]
修改已完成，等待王月测试，再提交code.
![010](https://cloud.githubusercontent.com/assets/20236838/18236670/3a662b14-735b-11e6-94dd-a0eb24e3496e.png)
![011](https://cloud.githubusercontent.com/assets/20236838/18236673/444f7266-735b-11e6-8015-2d9e525254a6.png)
