### ISSUE TITLE
测试接收明细退货时异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#464]
https://github.com/kakazuo/yimengtech/issues/445

**Comment by neverlosewy818** [comment]
测试结果：
1、使用山东测试环境打不开该界面
2、二级接收退货后，同批商品再在一级接收退货时报错
![qq 20160905180013](https://cloud.githubusercontent.com/assets/20236933/18244521/0be17310-7393-11e6-97d3-59695f0548ca.png)

**Comment by neverlosewy818** [comment]
测试已通过

**Comment by superman6666** [comment]
第一个问题已经新开测试任务
第二个问题是因为王月没更新代码所导致的
