### ISSUE TITLE
河南整包发货查询查不到数据

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#474]
![qq 20160906145746](https://cloud.githubusercontent.com/assets/20236933/18264363/68de7fb8-7442-11e6-8abc-847ef035be98.png)

**Comment by wangyubest** [comment]
截止2016-09-06 19:00分，测试了四个地方，分别为：大丰，山东，河南，华洛芙，都不能查到整包发货的数据。
具体效果已截图，明天附上具体步骤及截图效果。

**Comment by wangyubest** [comment]
1：整包进货
![043](https://cloud.githubusercontent.com/assets/20236838/18297035/726c058e-74e0-11e6-960f-d0cb468933ce.png)
2.整包入库
![044](https://cloud.githubusercontent.com/assets/20236838/18297046/832b2e04-74e0-11e6-9db3-b3f67997cb81.png)
3.入库单打印
![045](https://cloud.githubusercontent.com/assets/20236838/18297056/9542ea00-74e0-11e6-8936-88206d0a7401.png)
4.整包定价
![046](https://cloud.githubusercontent.com/assets/20236838/18297060/a47989de-74e0-11e6-9f2b-7ffaa39389ad.png)
5.整包发货
![047](https://cloud.githubusercontent.com/assets/20236838/18297065/b3da4a30-74e0-11e6-96d9-38a870c89d78.png)
6.进入后台调试
![048](https://cloud.githubusercontent.com/assets/20236838/18297081/c945f48c-74e0-11e6-8d45-8bfc8cedbff5.png)
7.调试完毕，查看数据库结果（结果显示数据库已成功添加此发货记录）
![049](https://cloud.githubusercontent.com/assets/20236838/18297273/eadfbaf0-74e1-11e6-8f0e-9ac8e8513ef4.png)
8.发货查询
![050](https://cloud.githubusercontent.com/assets/20236838/18297323/4610e12e-74e2-11e6-8b7b-19f0b5c6a387.png)
9.经排查，发现是ws中的发货查询中left关联了s_ws_StorageBatchStone（库存_包_副宝）表，这导致了没有副包的数据就显示不符合查询规则，故查询不到数据，经张伟同意已修改代码为left join，具体见效果图。
![051](https://cloud.githubusercontent.com/assets/20236838/18305126/9b2958ea-7518-11e6-84ea-868acf578e89.png)
![052](https://cloud.githubusercontent.com/assets/20236838/18305127/9b2cce9e-7518-11e6-855b-425d9d1108fa.png)
![053](https://cloud.githubusercontent.com/assets/20236838/18305124/9b228e52-7518-11e6-8a61-588dc2580926.png)
![054](https://cloud.githubusercontent.com/assets/20236838/18305128/9b2e4b70-7518-11e6-82c7-f0fa4fdf2548.png)
![055](https://cloud.githubusercontent.com/assets/20236838/18305125/9b29390a-7518-11e6-9027-9a9ce52c8794.png)
![056](https://cloud.githubusercontent.com/assets/20236838/18305129/9b3007bc-7518-11e6-8340-5e5c393bd8cb.png)
代码已提交，等待王月测试。
![057](https://cloud.githubusercontent.com/assets/20236838/18305432/1e2991fa-751a-11e6-8abd-0598f31f6db3.png)

**Comment by wangyubest** [comment]
心得：
因为hql与sql之间是有区别的，所以使用join，Hibernate是不会帮我们转换成left join而是转换成inner join,所以为了确保数据的准确性及稳定可靠，建议采用left join，这样都会以左边的数据作为基础，有则显示（left join 表），无则不显示数据（left join 表），这样有和没有都可以查到数据了。
