### ISSUE TITLE
更新山东测试库、山东正式库、重启华洛芙正式库

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#477]
#1. 更新山东测试库

**开始时间**： 2016.09.06.12:00
**结束时间**：2016.09.06.13:00
**是否已通知用户（时间，历时等）**：是
**更新内容**：
   1.客户信息页面增加导出按钮，导出当前门店所有客户信息
   2.重定价后打印模板错误
**更新准备工作**：表修改的sql,为process表中新加字段并赋值0
**公司参数**：无
**更新的svn revision**：6321
**更新完是否已验证**：已验证
**更新中遇到的问题**：无
**更新完成是否已通知用户**：是
**备注**：
给客户使用后，发现山东测试库数据太过老旧，暂时先将我们的山东测试服务器连给他们用
#2. 更新山东正式库

**开始时间**： 2016.09.06.22:30
**结束时间**：2016.09.07.00:00
**是否已通知用户（时间，历时等）**：是
**更新内容**：
1.客户信息页面增加导出按钮，导出当前门店所有客户信息
2.重定价后打印模板错误
**更新准备工作**：表修改的sql,为process表中新加字段并赋值0
**公司参数**：无
**更新的svn revision**：6321
**更新完是否已验证**：已验证
**更新中遇到的问题**：无
**更新完成是否已通知用户**：是
**备注**：无
#3. 重启华洛芙正式库

**开始时间**： 2016.09.06.22:00
**结束时间**：2016.09.07.01:40
**是否已通知用户（时间，历时）**：是
**更新内容**：明细发货查询导出功能
**更新准备工作**：将myutil3.3覆盖至正式库
**公司参数**：无
**更新的svn revision**：无
**更新完是否已验证**：是
**更新中遇到的问题**：无
**更新完成是否已通知用户**：是
**备注**：
更新后导出依然无法使用
报错如下：
java.lang.NoSuchMethodException: Proc.Service.WS.WsServiceImpl.setResultRSCList(java.util.List)
经商讨最终将测试库的war包更新至正式库后正常使用

**Comment by kakazuo** [comment]
重启华洛芙环境的时候记得验证下发货明细导出是否正常
