### ISSUE TITLE
品名定义页面

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#480]
商品补货模块中的品名定义，在维护品名属性的时候，无宝石、无成色的商品（如卖品绳）无法维护。
页面：WEB-INF/Procedure/Primary/SU/ItemNameDefinition.js

**Comment by superman6666** [comment]
首先跟大丰沟通具体的需求，沟通过程中让大丰填写了一张excel表格，然后我再根据表格去修改，具体表格如下：
![qq 20160907143529](https://cloud.githubusercontent.com/assets/20296755/18302199/f4693052-7508-11e6-93a9-a8de995703f3.png)
功能已做好，等待王月测试时再提交代码
王月要测试
我提交了代码
