### ISSUE TITLE
成本导入后不提示导入成功

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#481]
ie控制台输出  'showSuccessInfo' 未定义

**Comment by superman6666** [comment]
问题已找到，是myutil-3.3.js的showSuccessInfo没有定义，解决方法是删除showSuccessInfo
![qq 20160906180947](https://cloud.githubusercontent.com/assets/20296755/18270124/f12275c6-745d-11e6-857d-1ca8c3d82476.png)
![qq 20160906181257](https://cloud.githubusercontent.com/assets/20296755/18270130/fd517130-745d-11e6-96ed-f951e1bafd90.png)
问题已解决，等待王月测试时再提交代码
代码已提交，王月正在测试
