### ISSUE TITLE
大丰明细导入没有成色可以导

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#498]
大丰的明细导入中，银饰和镶嵌类商品没有成色可以导入。
![058](https://cloud.githubusercontent.com/assets/20236838/18340789/86253e3e-75d9-11e6-8258-9697f74bffaa.png)
![059](https://cloud.githubusercontent.com/assets/20236838/18340797/8c3f10ce-75d9-11e6-8485-6c4f87a9601f.png)
修改后：明细导入珠宝类，珠宝没有成色。
![default](https://cloud.githubusercontent.com/assets/24468189/22962152/13576e6a-f386-11e6-8689-1ccccee72617.png)

**Comment by mawenhao** [comment]
测试通过
