### ISSUE TITLE
销售票据不合格，要求显示：产品金价，原价，工费，优惠情况

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#554]
1.销售单中增加：产品金价，原价，工费，优惠情况
要求：素金类货品要显示牌价、原价金额、工艺费、优惠情况；非素金类货品要显示原价、优惠情况。  
![1](https://cloud.githubusercontent.com/assets/20296755/18676403/0c4ec0a4-7f88-11e6-8adc-bf81ed70a4fd.png)
修改后结果如下图：
素金：
![qq 20160921134243](https://cloud.githubusercontent.com/assets/20296755/18699826/43226256-8006-11e6-9531-f366d85bef20.png)
非素金：
![qq 20160921142303](https://cloud.githubusercontent.com/assets/20296755/18699951/ffe87d80-8006-11e6-86e5-eb9d250b5f47.png)

2.在开发期间客户发现一个bug，在换售是合计金额不正确
![qq 20160921133536](https://cloud.githubusercontent.com/assets/20296755/18698918/60312d24-8000-11e6-9295-09fc8fd59b1a.png)

此问题已经修改好了，（主要原因是在合计金额的时候减去了补偿费，应该是加上补偿费）修改结果如下图：
![qq 20160921143033](https://cloud.githubusercontent.com/assets/20296755/18700112/15ee77b4-8008-11e6-99fc-584b40199668.png)

**Comment by superman6666** [comment]
单子已改好 code已提交 请测试

**Comment by mawenhao** [comment]
测试完毕通过
