### ISSUE TITLE
华洛芙门店退货增加打印功能

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#558]
经与李浩沟通，门店退货页面需要增加打印功能，打印数据按照，成色，类别进行分组。模板如下：
![062](https://cloud.githubusercontent.com/assets/20236838/18627388/3fa04320-7e8d-11e6-8904-bd8626938670.png)

**Comment by wangyubest** [comment]
现在的任务状态为，接下来还有三个单子需要写后台方法，因为门店退货界面有4个按钮，每一个按钮对应出来的打印数据不一样，现在将1000件的货能实现打印，接下来实现按单号和选择打印，最后再按照条码进行打印。
![063](https://cloud.githubusercontent.com/assets/20236838/18734398/8ea1d194-80a6-11e6-808a-6da5d19db4ac.png)

**Comment by wangyubest** [comment]
所有功能已完成，code已提交，等待测试。

**Comment by mawenhao** [comment]
测试完毕，未发现问题
