### ISSUE TITLE
镶嵌类货品调换时补差金额合计小写，大写都显示乱码，只显示支付方式合计					

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#562]
在旧宝回收时合计金额乱码
旧宝回收截图如下：
![qq 20160921143922](https://cloud.githubusercontent.com/assets/20296755/18700825/f4c7cc94-800b-11e6-962c-4a23cc74d4d4.png)

乱码截图如下：
![1](https://cloud.githubusercontent.com/assets/20296755/18676647/e11864b6-7f88-11e6-9609-ca43c9843333.png)

此问题已经修改好了，修改结果如下：
![qq 20160921144253](https://cloud.githubusercontent.com/assets/20296755/18700830/fee96d18-800b-11e6-893a-7c85974b3180.png)

**Comment by superman6666** [comment]
单子已改好  code已提交 请测试

**Comment by mawenhao** [comment]
测试通过
