### ISSUE TITLE
河南明细汇总查询不到数据

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#569]
参考： https://github.com/kakazuo/yimengtech/issues/568

**Comment by wangyubest** [comment]
经调试及写SQL发现，造成查询不了数据的原因是因为翡翠厂当时的需求里面要求根据成本区间查询汇总的数据，而河南的数据里面没有用到成本表，成本表为空，这样就导致了查询数据为空，解决方法是把翡翠厂的方法单独写出来，根据公司参数去调用查询的语句。
公司参数：07300 是否根据成本价查询汇总数据（名称）  0：不根据成本价去查，1：根据成本价去查询。
![071](https://cloud.githubusercontent.com/assets/20236838/18867559/4d7d3e3a-84d7-11e6-8d24-78b0add02983.png)
