### ISSUE TITLE
商品跟踪发现一个bug

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#57]
商品跟踪，用证书号跟踪会出现有的证书号找不到商品的情况
但是用该证书号对应的条码去跟踪就能找到

**Comment by wangyubest** [comment]
经测试没发现该问题，从批发到入库定价，再跟踪条码可以跟踪到。导致此现象的原因可能是用户主宝证书输入错误，或者该件货的进货---->发货这一流程有问题，解决办法：下次遇到的时候直接将该条数据与能跟踪到的数据进行对比解决。
