### ISSUE TITLE
首饰销售时，收旧报错

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#58]
![qq 20160706105448](https://cloud.githubusercontent.com/assets/20236933/16606148/1636cea6-4368-11e6-8fce-5959f6953fd3.png)

**Comment by kakazuo** [comment]
按照步骤重现没有发现问题，叫客户重试一下

**Comment by neverlosewy818** [comment]
测试版本不能打印，需去tools中注册
