### ISSUE TITLE
华洛芙柜组进销存查询全部门店数据不对

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#584]
![qq 20160926093534](https://cloud.githubusercontent.com/assets/19886532/18820062/9e6e298c-83cc-11e6-8994-f10d150315dc.png)
9月1日到9月26日销售数据不对
![qq 20160926093527](https://cloud.githubusercontent.com/assets/19886532/18820069/bb072a30-83cc-11e6-93c4-73401490a29a.png)

9月22日初始化其中信阳大商新玛特后数据不对

**Comment by superman6666** [comment]
![qq 20160926195930](https://cloud.githubusercontent.com/assets/20296755/18833554/c7ab0e08-8423-11e6-8d9b-e268448b9662.png)
主要原因是日期没有重置
![qq 20160927133536](https://cloud.githubusercontent.com/assets/20296755/18861417/9b44abd2-84b7-11e6-8cd4-11b3b294084f.png)

问题已解决，请测试
