### ISSUE TITLE
首饰销售页面，发现两个 BUG

### ISSUE THREAD

**Issue by mawenhao** [kakazuo/yimengtech#590]
问题1：
首饰销售页面下，填写品牌，营业员，实际价格后 ，点击添加按钮
正常情况下，应该报出信息输入不全或者类似提示，但这边没有任何校验
![qq 20160926133312](https://cloud.githubusercontent.com/assets/20239598/18823553/d3e83474-83ed-11e6-9d87-b7dce722be40.png)
问题2：
首饰销售页面下，正常添加一条数据后，实际价格处任意填写数字，点击添加，可以输出结果
![qq 20160926133719](https://cloud.githubusercontent.com/assets/20239598/18823632/60a76fd8-83ee-11e6-9414-c778092b9688.png)

**Comment by hyh199111** [comment]
![default](https://cloud.githubusercontent.com/assets/24468189/22728307/30bc3fa8-ee18-11e6-8081-c8499a51e655.png)
没有输入条形码时会提示：信息不完整。
![default](https://cloud.githubusercontent.com/assets/24468189/22728338/509ac484-ee18-11e6-820c-2ee2054cb5e1.png)
第一条数据添加成功之后，只填写实际金额将不能添加商品。

**Comment by mawenhao** [comment]
测试通过
