### ISSUE TITLE
大丰分秤导入导不了

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#619]
大丰整包分秤页面有条码导入，卡在导入页面，没有提示报错信息。
经调查：发现  1.没有副宝，但是缺有副宝重量0.00
                        2.类别为：戒指(八心八箭)的()为英文的括号，所有系统找不到该类别，但是未提示错误信息。
              跟进：已提示大丰的相关人员修改数据，并进行提示的更改

**Comment by wangyubest** [comment]
导入提示错误信息已修改，等待测试。
![074](https://cloud.githubusercontent.com/assets/20236838/18950090/c082c0a4-8670-11e6-9f70-807e84c35227.png)

**Comment by mawenhao** [comment]
测试通过
