### ISSUE TITLE
重庆抵扣

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#620]
长期问题，年底之前做完。
2016-09-29：与XJX沟通了解大致需求。
![073](https://cloud.githubusercontent.com/assets/20236838/18945441/2b27e0c4-865d-11e6-98e0-edd18d7a8781.jpg)
2016-10-09: 再次与XJX沟通了解具体需求，并拟写需求报告文档。（已完成）
2016-10-10：具体细节化，把业务流程疏通一遍，遇到的问题已记录，等待与XJX协商再次解决。
2016-10-11：与XJX讨论具体需求，以及复杂功能如何实现问题，通过草稿，画图等方式来解决。
2016-10-12：与XJX和YJ讨论重庆单子的问题，单子已经通过QQ形式发于我，王月已经确定单据他做完了。
2016-10-13：开始编码工作，新建基础数据实体类（DeductibleSetup ）
    private int ds_id;                               //主键ID
        private String ds_name;                   //抵扣商品名称
        private BigDecimal ds_roportion;     //抵扣占比
    private Supplier ds_supplier1;           //所属供应商1
    private Supplier ds_supplier2;           //所属供应商2
    private Supplier ds_supplier3;           //所属供应商3
    private Supplier ds_supplier4;           //所属供应商4
    private Supplier ds_supplier5;           //所属供应商5
用于用户自己控制赠送的抵扣商品，以及抵扣占比。
2016-10-25 ：与XJX和YJ沟通打印单子的事情，并且制作单据。
![102](https://cloud.githubusercontent.com/assets/20236838/19711879/ad13e9f2-9b6b-11e6-8f24-b457e73fd6ff.png)
![101](https://cloud.githubusercontent.com/assets/20236838/19711884/b45bf6f0-9b6b-11e6-827f-33de92e9ddc4.png)

**Comment by wangyubest** [comment]
![010](https://cloud.githubusercontent.com/assets/20236838/20588529/d273bbf4-b250-11e6-8962-480ca5e70548.png)

**Comment by mawenhao** [comment]
测试完毕
