### ISSUE TITLE
华洛芙收旧统计页面导出需要修改

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#635]
1，问题：首先华洛芙客户说查询数据跟导出数据不一致，导出多了暂存数据
解决方法：现在就是让他在导出的excel做筛选就ok了，把暂存的数据过滤掉

2，问题：客户想在导出的excel表格中增加两列（回购金额 补偿金额）
3，问题：客户想可以一次性导出全部门店的数据
由于问题2,3修改比较麻烦，并且会影响其他功能，所以我跟客户沟通并提出了我的想法
我的想法是：给他们加一个导出按钮 导出的是一个excel表格 表格里面的内容为页面上查询出来的数据
由于客户有更紧急的事 所以决定10.9继续沟通此事！
经沟通决定给他们重新做一个导出按钮。
功能已做好，请测试。

**Comment by mawenhao** [comment]
测试通过
