### ISSUE TITLE
暂存旧品换售后，再退货旧品状态为退还，不可再参加换售。

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#640]
暂存旧品换售后，再退货旧品状态为退还，不可再参加换售。
![qq 20161009093210](https://cloud.githubusercontent.com/assets/19886532/19216930/4d61594c-8e03-11e6-92c7-0f2baaabef68.png)

**Comment by wangyubest** [comment]
![001](https://cloud.githubusercontent.com/assets/20236838/19466532/3d66253a-953e-11e6-8ef4-26c819a8cf8a.png)
销售一笔业务，选择有旧料的东西，旧料暂存页面状态改为：已使用。
如果该笔业务出现：作废/全退 ,那么旧料暂存的东西则应该变为：可用。
BUG已解决，等待测试。

**Comment by mawenhao** [comment]
测试通过
