### ISSUE TITLE
明细汇总增加合计

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#65]
明细汇总增加合计

**Comment by kakazuo** [comment]
等张老师确定合计方法后开始

**Comment by wangyubest** [comment]
库存明细汇总页面，用户选择公司，其他条件根据需求选择，点击刷新，将查询的数据加载到Grid中，底部合计栏显示出所有数据合计信息，包括（件数，零售价，料重，主宝件数，主宝重量）。 @kakazuo

**Comment by kakazuo** [comment]
# 1 方法 getStorageDetailCountQuery_total中修改result数组的默认值
