### ISSUE TITLE
翡翠厂【汇总查询】导出合计排序错乱

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#651]
参考：https://github.com/kakazuo/yimengtech/issues/650

**Comment by wangyubest** [comment]
![079](https://cloud.githubusercontent.com/assets/20236838/19256678/d282ea0c-8f9b-11e6-97f4-0f84faa4fee9.png)
修改完成，等待测试。

**Comment by mawenhao** [comment]
测试通过，但发现页面上存在BUG，已记录
