### ISSUE TITLE
大丰门店退货合计与导出数据不对

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#662]
大丰门店退货页面底部合计与导出的数据不对。
![082](https://cloud.githubusercontent.com/assets/20236838/19261227/47222708-8fc2-11e6-9fbd-581338416e02.jpg)
![083](https://cloud.githubusercontent.com/assets/20236838/19261228/472db62c-8fc2-11e6-9e02-cedd0d44f799.jpg)

**Comment by wangyubest** [comment]
经过调查发现，是由于传递参数导致的。
![080](https://cloud.githubusercontent.com/assets/20236838/19261337/0901c662-8fc3-11e6-9da2-8223e197a5cc.png)
![081](https://cloud.githubusercontent.com/assets/20236838/19261338/090a2a50-8fc3-11e6-8113-dc933defe5d5.png)
由于传递的参数为1，后台默认查询全部数据，所有导致数据不对，由于是门店退货，后台对应的参数是5，所以页面上应该改为5，这样就查询正确了。
![084](https://cloud.githubusercontent.com/assets/20236838/19261387/579abab8-8fc3-11e6-91fa-bca387b70698.png)
![085](https://cloud.githubusercontent.com/assets/20236838/19261388/57a2827a-8fc3-11e6-89d8-ecd856986137.png)

**Comment by mawenhao** [comment]
测试通过
