### ISSUE TITLE
华洛芙设置基准折扣异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#675]
参考：https://github.com/kakazuo/yimengtech/issues/674

**Comment by superman6666** [comment]
![qq 20161013165752](https://cloud.githubusercontent.com/assets/20296755/19342863/3d2d2f5e-9166-11e6-8647-268097472804.png)
导致保存报错的主要原因是美尔伦的基准折扣都为0，但后台接收到的为空。
解决方法：把美尔伦的基准折扣都填0再保存就行了
问题已解决！
