### ISSUE TITLE
山东退货单数据异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#681]
参考：https://github.com/kakazuo/yimengtech/issues/678

**Comment by wangyubest** [comment]
经调查认证，打印的数据没异常，只是在选择发货的打印数据少了成本价和副宝粒数。
![086](https://cloud.githubusercontent.com/assets/20236838/19373203/e5156950-91f4-11e6-88c9-7285594c177e.png)
![087](https://cloud.githubusercontent.com/assets/20236838/19373212/f5208c6c-91f4-11e6-8c01-88e4f6a067d5.png)
![088](https://cloud.githubusercontent.com/assets/20236838/19373214/f52387b4-91f4-11e6-9581-3d7ed03bcfcc.png)
![089](https://cloud.githubusercontent.com/assets/20236838/19373216/f527173a-91f4-11e6-99de-89584a7f781d.png)
![090](https://cloud.githubusercontent.com/assets/20236838/19373213/f521674a-91f4-11e6-81af-4890788ab940.png)
![091](https://cloud.githubusercontent.com/assets/20236838/19373215/f525fc2e-91f4-11e6-9b8e-d80b4aa92d12.png)
![092](https://cloud.githubusercontent.com/assets/20236838/19373279/5c54e98c-91f5-11e6-8a9f-fcb5e8efb448.png)
![093](https://cloud.githubusercontent.com/assets/20236838/19373218/f54e5a16-91f4-11e6-9200-0e3537db02e0.png)
