### ISSUE TITLE
华洛芙牌价浮动启用报异常

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#707]
![qq 20161019110517](https://cloud.githubusercontent.com/assets/20236933/19504338/1edeb09c-95ec-11e6-8685-96db3be94b58.png)

**Comment by neverlosewy818** [comment]
本地不管怎么操作都是正常的，远程操作客户那边启用就报错
本地直接连接华洛芙正式库操作后也报错，怀疑是数据问题，具体还需跟代码解决

**Comment by superman6666** [comment]
我远程去看他们操作是没问题的
