### ISSUE TITLE
店铺货品下柜后，只允许退货和上柜，不允许再调拨至其他店铺 

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#743]
问题1,店铺货品下柜之后 不允许调拨 
解决方法：判断是否在柜组，如果不在柜组则不允许调拨。由于只是华洛芙有这种需求，所以加了公司参数，公司参数为：07301 下柜之后是否允许调拨 0-允许，1-不允许
该问题已解决，效果如下图：
![qq 20161026110315](https://cloud.githubusercontent.com/assets/20296755/19714840/d507e7fc-9b83-11e6-9dda-776125df85d8.png)
2.在解决此问题的过程中发现了本页面一个bug，bug为：点击删除按钮没有反应，删不掉东西。
此bug已修复
3.最后又想到一个问题，就是在这边把商品先加载到grid里面，再去柜组给他下柜，再去调拨就还可以去调拨，这是一个非常规操作导致的，现在加了控制，能控制到这种非常操作不允许调拨
此问题已解决
![qq 20161027114231](https://cloud.githubusercontent.com/assets/20296755/19753884/1ecfc938-9c3b-11e6-9dcb-fefafa493a9a.png)

问题已解决 请测试

**Comment by mawenhao** [comment]
测试通过
