### ISSUE TITLE
目前针对在设置扣损耗调换的规则时，损耗部分只能在金损费上设置应扣金额，系统金价变更一次就需要计算后调整一次，增加工作时间

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#760]
![qq 20161101100324](https://cloud.githubusercontent.com/assets/20296755/19877573/61a2146c-a01b-11e6-89a6-48709658e963.png)
![qq 20161101100943](https://cloud.githubusercontent.com/assets/20296755/19877572/61a05974-a01b-11e6-9b36-ad73a8de310f.png)

之前的工费补偿费算的净重的100% 他们要求是按旧金减重百分比来算。
由于这是个性化需求  所以加了公司参数
公司参数为：07304 控制工费补偿费是否乘以旧金减重百分比  0-允许，1-不允许 
功能已做好，请测试！

**Comment by mawenhao** [comment]
测试通过
