### ISSUE TITLE
华洛芙首饰销售明细查询页面旧品信息列需要修改

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#769]
要求：换新销售的旧品信息列必须全部为正数，本地退货的旧品信息列必须全部为负数。如果补偿费为负数，则退货时显示为正数
![1](https://cloud.githubusercontent.com/assets/20296755/19888792/e4c55642-a06b-11e6-8070-00c1c6536258.png)
修改后的效果如下图：
![qq 20161102164657](https://cloud.githubusercontent.com/assets/20296755/19924178/cebff05e-a125-11e6-8cb3-8add8d6e55f8.png)

功能已做好 请测试！

**Comment by mawenhao** [comment]
测试通过
