### ISSUE TITLE
华洛芙柜组进销存与门店商品查询查出的数据相差一件

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#772]
![qq 20161102135251](https://cloud.githubusercontent.com/assets/20236933/19918286/dd5fdbae-a104-11e6-85e9-19965059334f.png)
![qq 20161102135256](https://cloud.githubusercontent.com/assets/20236933/19918288/e333e1e2-a104-11e6-89c6-65b64861acd1.png)

**Comment by superman6666** [comment]
导致这个问题的原因是在初始化的那天上午门店使用了系统，销售出去了一件料重为46.6的货
![qq 20161103112154](https://cloud.githubusercontent.com/assets/20296755/19954978/2896f7b6-a1b8-11e6-9694-6674d130b718.png)

解决方法 等到下个月1号从新初始化！
