### ISSUE TITLE
门店操作换售产品的销售作废之后，旧金同样需要作废，不能出现在旧料统计功能的计算过程中

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#773]
门店操作换售产品的销售作废之后，旧金同样需要作废，不能出现在旧料统计功能的计算过程中
![qq 20161102165204](https://cloud.githubusercontent.com/assets/20296755/19924285/46b91b8a-a126-11e6-93e9-79d2c482d4a6.png)
![qq 20161102165405](https://cloud.githubusercontent.com/assets/20296755/19924286/46dbfc90-a126-11e6-8008-4033f77af47d.png)
![qq 20161102165336](https://cloud.githubusercontent.com/assets/20296755/19924307/592a6b8e-a126-11e6-8db8-6ef24ad582f8.png)
功能已做好 请测试！

**Comment by mawenhao** [comment]
测试通过
