### ISSUE TITLE
华洛芙票据打印-销售单

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#779]
需要系统服务公司系统设置退货业务发生时，单据内的货名栏应调整为柜组+大类，例如老凤祥黄金柜组挂件，显示为老凤祥黄金挂件，去掉柜组二字，目前情况是店铺不同柜组的货品，成色一致，销售时售后票若不显示柜组+大类，店铺需要售后票上方备注，影响店铺做账		
原来的票据如下：
![1](https://cloud.githubusercontent.com/assets/20296755/19964504/0383038a-a1fd-11e6-8724-fa6918d72296.png)

修改后的票据如下：
![qq 20161103194607](https://cloud.githubusercontent.com/assets/20296755/19964704/4fe318e0-a1fe-11e6-9f8e-dbe9b5f044e9.png)

修改了模板6-5，js，后台
此票据已修改好，请测试！

**Comment by mawenhao** [comment]
测试通过
