### ISSUE TITLE
华洛芙票据打印-调拨单

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#780]
需要系统服务公司系统设置调拨业务发生时，单据内的成色栏应调整为货品（包含品牌成色）、大类栏应显示颈饰、腕饰等，目前情况是调拨单不显示品牌，大类栏显示的是细类，不方便交接货品			
原来的票据如下：
![2](https://cloud.githubusercontent.com/assets/20296755/19964547/4394c62a-a1fd-11e6-856c-47b7afa06eea.png)

修改后的票据如下：
1，调拨页面：
![qq 20161104112632](https://cloud.githubusercontent.com/assets/20296755/19993733/d9459430-a282-11e6-972f-493ca5284695.png)
2，调拨单子
![qq 20161103200232](https://cloud.githubusercontent.com/assets/20296755/19993738/e9e7920c-a282-11e6-86f3-f599595286a5.png)
3，在修改的时候发现的bug
![qq 20161104113059](https://cloud.githubusercontent.com/assets/20296755/19993742/ebda991a-a282-11e6-983e-4b0f313519de.png)
4，补打页面
![qq 20161104112301](https://cloud.githubusercontent.com/assets/20296755/19993750/f8820d1a-a282-11e6-8dcb-979fed3eff53.png)
5，补打单子
![qq 20161104112442](https://cloud.githubusercontent.com/assets/20296755/19993751/f8c8749e-a282-11e6-9b42-0717529a23f4.png)
修改了模板5-6，js，后台
功能已做好，请测试！

**Comment by mawenhao** [comment]
测试通过

**Comment by mawenhao** [comment]
测试通过
