### ISSUE TITLE
华洛芙票据打印-退货单

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#781]
需要系统服务公司系统设置退货业务发生时，单据内的成色栏应调整为货品（包含品牌、成色）目前情况是单据只显示成色不显示品牌，无法区分是老凤祥品牌货品还是帝曼龙品牌货品，不方便记账
原来的票价如下：
![1](https://cloud.githubusercontent.com/assets/20296755/19998095/ba64e4f8-a2a5-11e6-8904-41f6550f7b05.png)
修改后的票据如下：
加了品牌：
![qq 20161104154134](https://cloud.githubusercontent.com/assets/20296755/19998105/c831d41a-a2a5-11e6-81b8-3781da2d4343.png)
此票据已修改好，请测试！

**Comment by mawenhao** [comment]
测试通过

**Comment by mawenhao** [comment]
测试通过

**Comment by mawenhao** [comment]
测试通过
