### ISSUE TITLE
华洛芙票据打印-发货单

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#782]
需要系统服务公司系统设置发货业务发生时，单据内的成色栏应调整为货品（包含品牌、成色）目前情况是单据只显示成色不显示品牌，无法区分是老凤祥品牌货品还是帝曼龙品牌货品，不方便记账
原来的票据如下：
![2](https://cloud.githubusercontent.com/assets/20296755/19998154/0ef670ae-a2a6-11e6-9dfe-2de7220eed42.png)

修改后的票据如下：
选择发货页面的送交单：

![qq 20161107141503](https://cloud.githubusercontent.com/assets/20296755/20048139/3f40c1d2-a4f5-11e6-84bf-f152d83e7638.png)
![qq 20161107141545](https://cloud.githubusercontent.com/assets/20296755/20048137/3f356b98-a4f5-11e6-9c28-72309331ee9f.png)
单据发货的送交单：
![qq 20161107141703](https://cloud.githubusercontent.com/assets/20296755/20048136/3f3431a6-a4f5-11e6-980d-e7693629f670.png)
![qq 20161107141736](https://cloud.githubusercontent.com/assets/20296755/20048138/3f3d8350-a4f5-11e6-98fd-7a1f9590771a.png)

票据已修改好，请测试！

**Comment by mawenhao** [comment]
测试通过
