### ISSUE TITLE
大丰收旧统计页面旧料在作废之后还存在

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#791]
问题：大丰收旧统计页面旧料在作废之后还存在
要求：旧料在作废之后收旧统计页面不应该存在！
问题已解决，过程如下：
![qq 20161110140511](https://cloud.githubusercontent.com/assets/20296755/20166857/9dcecef6-a752-11e6-8ef3-658824b28d4f.png)
![qq 20161110141618](https://cloud.githubusercontent.com/assets/20296755/20166859/9dd0828c-a752-11e6-85ce-10606ca9302c.png)
![qq 20161110141756](https://cloud.githubusercontent.com/assets/20296755/20166860/9dd1a900-a752-11e6-9f9f-d35df3a26dff.png)
![qq 20161110141919](https://cloud.githubusercontent.com/assets/20296755/20166858/9dceee0e-a752-11e6-832c-8c60e76541d6.png)
![qq 20161110142031](https://cloud.githubusercontent.com/assets/20296755/20166861/9dd6a414-a752-11e6-8125-79d6b7a6c05a.png)
![qq 20161110142326](https://cloud.githubusercontent.com/assets/20296755/20166862/9de4c8dc-a752-11e6-94db-3bf7e8a9c01f.png)
![qq 20161110142604](https://cloud.githubusercontent.com/assets/20296755/20166863/9e025500-a752-11e6-9abb-f4dd4082dc2c.png)
![qq 20161110142741](https://cloud.githubusercontent.com/assets/20296755/20166864/9e059d28-a752-11e6-9d14-5f862bac3b74.png)
![qq 20161110142914](https://cloud.githubusercontent.com/assets/20296755/20166865/9e09efb8-a752-11e6-8fdc-77874e60a331.png)

功能已改好，请测试！

**Comment by mawenhao** [comment]
测试通过
