### ISSUE TITLE
解决翡翠厂选择退货之后公司汇总查询数据不变问题

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#795]
选择一个条码，选择退货，完成退货之后，公司汇总数据应该减去所退数据，现在发现数据并未改变，
出现的原因是：选择退货的时候修改了StorageDetailProcess的action=4,标记为退货,但是汇总查询的条件一直都会存在action=4,所以无论怎样查询,条件都满足.
![001](https://cloud.githubusercontent.com/assets/20236838/20091026/6542f360-a5cb-11e6-9ff2-a08f4c6546db.png)
解决办法:
![002](https://cloud.githubusercontent.com/assets/20236838/20091078/ccaa2b68-a5cb-11e6-8593-a904c0c8e076.png)

**Comment by mawenhao** [comment]
测试通过
