### ISSUE TITLE
华洛芙票据打印-调拨单（汇总单）

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#798]
原来的单子如下图：
![qq 20161109154844](https://cloud.githubusercontent.com/assets/20296755/20130782/19d95918-a694-11e6-93dc-1753b88876a8.png)

修改后的单子如下图：
调拨页面：
![qq 20161109155456](https://cloud.githubusercontent.com/assets/20296755/20131126/7e7e7fc2-a696-11e6-8a98-a2b51535edea.png)
补打页面：
![qq 20161109155707](https://cloud.githubusercontent.com/assets/20296755/20131127/7e986400-a696-11e6-8d69-577c96037de5.png)
修改之后两个页面打印的单子
![qq 20161109160536](https://cloud.githubusercontent.com/assets/20296755/20131128/7ea792ea-a696-11e6-840f-69269c5b67ca.png)

单子已改好，请测试！

**Comment by mawenhao** [comment]
测试通过
