### ISSUE TITLE
tools里面的明细初始化页面加删除按钮

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#809]
要求：tools里面的明细初始化页面加删除按钮
删除按钮已经增加好，后台先删除明细表，再删除批次表。
效果如下图：
![qq 20161124164511](https://cloud.githubusercontent.com/assets/20296755/20591843/8cb9e808-b265-11e6-911f-df2fd36993fc.png)
功能已做好，请测试!

**Comment by neverlosewy818** [comment]
测试通过，未发现任何问题
