### ISSUE TITLE
华洛芙首饰销售明细查询页面的旧金列出现同一单会重复

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#825]
问题：华洛芙首饰销售明细查询页面的旧金列出现同一单会重复
页面的查询条件如下：
![qq 20161117144839](https://cloud.githubusercontent.com/assets/20296755/20379082/26b48ea4-acd5-11e6-9f16-e448a68185a9.png)

出错的业务号为：NO-2016111101311，NO-2016111200461
问题截图如下：
![1](https://cloud.githubusercontent.com/assets/20296755/20378822/71d69fdc-acd3-11e6-92f2-7905d67f66a6.png)
导致问题的原因是：因为在导出的时候读数据是一次读取1000条，而在对比业务号的时候重新读取1000条时业务号会重新初始化变为空。
解决方法：把变量申明在一个类里面就ok了
问题已解决，请测试！

**Comment by mawenhao** [comment]
测试通过
