### ISSUE TITLE
华洛芙销售单出现乱码

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#827]
问题：华洛芙销售单出现乱码
乱码截图如下：
![1](https://cloud.githubusercontent.com/assets/20296755/20421069/a94aef08-ad9c-11e6-8903-6848eef0c22d.png)
导致这个问题的原因是：补偿费>=1000 或者 补偿费<=-1000
因为超过三位数js传过去的补偿费会有逗号分隔符，所以在模板里面补偿费参加算法的时候会导致零售价乱码，如下图：
![qq 20161118101157](https://cloud.githubusercontent.com/assets/20296755/20421168/3d919798-ad9d-11e6-909f-1b15c8a0c70f.png)

问题已解决 请测试！

**Comment by mawenhao** [comment]
测试通过
