### ISSUE TITLE
翡翠厂结算明细和结算汇总数据不对应

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#845]
八月份问题:
经过SQL语句的对比,是因为在结算明细查询中,process的response等于1代表了退货,但是结算明细查询的条件只能为0,如果这件货再8月份已经结算完成,但是再10月退货,会更改8月份的结算的responese为1,所以再去查询明细数据的时候会少一件,汇总的数据不变.
十月份问题:
经过SQL的对比,是因为在10月份的时候,发生了4件退货的商品信息,在后台的处理逻辑上用负号进行了冲抵,这样就导致了结算明细会多出来退货的数据.
解决办法:
更改了结算明细查询中的response=0(去掉这个条件),就把结算与退货的商品都查询出来了,这样保证了数据的完整性,由于系统没有做退货查询的功能,所以增加了退货查询按钮,查询条件为:action = 40 and response =1,然后再将明细全部查询的数据减去退货的数据,就能得到的结算数据.
已完成,待测试.

**Comment by mawenhao** [comment]
测试通过
