### ISSUE TITLE
结算汇总查询页面导出数据错位

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#850]
问题：结算汇总查询页面导出数据错位（二级批发价和结算价列放反了）
截图如下：
![qq 20161128161655](https://cloud.githubusercontent.com/assets/20296755/20661354/5af75806-b589-11e6-9623-40b1c0d374cf.png)

功能已做好，请测试！

**Comment by mawenhao** [comment]
测试通过
