### ISSUE TITLE
河南增加批量调整工费

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#855]
需求： 河南增加批量调整工费 
有公司参数：07305 批量修改成标签工费   0-无，1-启用
步骤如下：根据上图设置好的工费批量修改下图的工费
![qq 20161202104327](https://cloud.githubusercontent.com/assets/20296755/20821405/28ce3cae-b87d-11e6-9e8e-85c7d9b47a92.png)
![qq 20161202104956](https://cloud.githubusercontent.com/assets/20296755/20821404/28898de8-b87d-11e6-81a8-9be62647993c.png)

功能已做好 请测试！

**Comment by mawenhao** [comment]
测试通过
