### ISSUE TITLE
重庆新需求功能

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#857]
1:整包发货中成色控件只能跨本级成色,如:足金,只能是黄金下面的子类,18K只能为18K子类的东西.
![011](https://cloud.githubusercontent.com/assets/20236838/20743244/3c2a96d0-b710-11e6-9479-516bd3195255.png)
2:超级账号可以设置分秤权限,通过了解指导,已知道如何设置.
3:分秤页面中,工费一栏需更改为手动输入.
![012](https://cloud.githubusercontent.com/assets/20236838/20743308/99f9b124-b710-11e6-8a76-84812f0bff3a.png)
4:结算还款页面增加还款备注
![013](https://cloud.githubusercontent.com/assets/20236838/20743365/e1579482-b710-11e6-86a5-7e06f87cc1de.png)
![014](https://cloud.githubusercontent.com/assets/20236838/20743393/03a58bc0-b711-11e6-9c99-6c9565c4c1f8.png)
5:旧料回收统计页面,经过沟通了解,系统中已经存在该功能,但需进一步更改,具体更改XJX考虑之后做打算再改进.

**Comment by mawenhao** [comment]
问题2，由于要改数据库，由王月测试
问题5，待测试，有修改

**Comment by mawenhao** [comment]
问题1,3,4测试通过
