### ISSUE TITLE
单据结算页面修改

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#861]
问题： 单据结算时按整个单子价格结算，计算每件结算金额时，将差额算入最后一件货
原因是：每件的结算价在存入数据库中表示都是四舍五入，所以导致结算汇总查询的结算价有误差
解决方法：在后台把误差算出来，最后把误差算入最后一件货
页面如下
![qq 20161208170802](https://cloud.githubusercontent.com/assets/20296755/20828478/b1491fe2-b8b2-11e6-8521-2b7b1187f864.png)
![qq 20161208171000](https://cloud.githubusercontent.com/assets/20296755/20828479/b1500bf4-b8b2-11e6-9bc5-cb2d89a13f51.png)

问题已解决，请测试！

**Comment by mawenhao** [comment]
测试通过
