### ISSUE TITLE
公司进销存bug

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#864]
问题：公司进销存的期初和期末不一致
原因：公司进销存的js里面的grid的期初字段并不是期初字段
解决方法：把js里面的grid的期初字段改为期初字段就ok了
修改后的期初和期初如下截图：
![qq 20161208135331](https://cloud.githubusercontent.com/assets/20296755/20999374/000d542c-bd4f-11e6-8fca-fb847fe2eb57.png)
![qq 20161208135358](https://cloud.githubusercontent.com/assets/20296755/20999373/00020e28-bd4f-11e6-94d0-46b14d1c832e.png)
问题已解决 请测试！

**Comment by feixianhui** [comment]
测试已通过
