### ISSUE TITLE
重庆结算查询页面

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#890]
设计页面，实体，表

**Comment by wangyubest** [comment]
![000012](https://cloud.githubusercontent.com/assets/20236838/21167731/7d761c34-c1e9-11e6-8224-5bf91f1cc15c.png)
![000013](https://cloud.githubusercontent.com/assets/20236838/21167732/7e95fefe-c1e9-11e6-96cb-c98e0a8603ce.png)
已开发完成，等待测试。

**Comment by wangyubest** [comment]
新增查询条件： 全部查询  立即结价查询   订货会结价查询
![000015](https://cloud.githubusercontent.com/assets/20236838/21209370/de648916-c2ae-11e6-84cb-28250c819954.png)

**Comment by mawenhao** [comment]
测试通过
