### ISSUE TITLE
商品跟踪页面增加显示成本列

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#891]
需求： 增加显示成本列
有公司参数：07108 商品跟踪是否显示各项成本 1 0-不允许，1-允许
界面如下：
![qq 20161212104405](https://cloud.githubusercontent.com/assets/20296755/21086527/5ab7b00a-c058-11e6-82db-a61b3280c110.png)

**Comment by feixianhui** [comment]
测试通过
