### ISSUE TITLE
商品跟踪页面显示库位之间的流转过程

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#892]
需求：商品跟踪页面显示库位之间的流转过程
公司参数： 07307  商品跟踪是否显示库位 1 0-不允许，1-允许
界面如下：
![qq 20161212105756](https://cloud.githubusercontent.com/assets/20296755/21086700/e2b1c7ba-c059-11e6-84a4-537bd8c52f80.png)
功能已做好，请测试！

**Comment by feixianhui** [comment]
测试通过
