### ISSUE TITLE
测试进销存bug

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#897]
走流程看进销存里的数据变化
1.明细：初始化后看进销存数据正常
1.整包：初始化后看进销存数据正常
走流程和郝永恒一起看  都正常！

**Comment by hyh199111** [comment]
1.一级账号完成，进货、定价、分称、发货流程。建立二级账号完成收货、入库、退货流程。
2.进入公司进销存页面查看期初、期末数据是否正确。并追踪货物信息。
