### ISSUE TITLE
会员功能

### ISSUE THREAD

**Issue by hyh199111** [kakazuo/yimengtech#901]
熟悉会员功能，业务需求。

**Comment by superman6666** [comment]
1.需求调研
![qq 20161227134030](https://cloud.githubusercontent.com/assets/20296755/21491780/22989e6c-cc3a-11e6-8145-95f3203f117b.png)

![qq 20161227134043](https://cloud.githubusercontent.com/assets/20296755/21491779/2294ea1a-cc3a-11e6-9943-4e1c6a2afa74.png)

**Comment by superman6666** [comment]
前期需求调研，研究会员，把以前写的会员部分代码copy到现在的项目中（12.13—12.28（11-5=6个工作日））

**Comment by hyh199111** [comment]
调换工费规则页面
1：分析页面功能。
2：设计页面。
