### ISSUE TITLE
华洛芙明细发货查询无法导出

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#910]
![qq 20161214141808](https://cloud.githubusercontent.com/assets/20236933/21171619/38045c46-c208-11e6-8700-74fc6dbda008.png)

**Comment by neverlosewy818** [comment]
导出数据只要一千多条，后台一直在走，十几分钟仍然无法导出

**Comment by superman6666** [comment]
我这边本地是可以正常导出，然后备份华洛芙最新数据也是可以正常导出，所以最后怀疑华洛芙数据库有问题 最后和王月商量准备重启华洛芙服务器再看是否能导出
