### ISSUE TITLE
重庆改进

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#912]
1.整包发货页面，成色修改按钮，禁用。
![000014](https://cloud.githubusercontent.com/assets/20236838/21175176/1bf5f762-c21c-11e6-9dab-7b5ab875f79c.png)
已完成，有公司参数， 07308 整包发货成色修改功能禁用 1 0：可使用，1：禁用

2. 结算还款页面点击还款按钮，备注栏输入一个单号，表示该笔为退货数据，则对应的抵扣额度应当减少。（插入一条 -的数据，单号为：退货作废）

3.额度明细页面，如果抵扣额度用光，开增值的时候加一句话，参与抵扣，额度已用光，超出额度部分金额已加入欠款。

4.结算还款页面，素金还欠不重复计入工费，因为在结算中心下发的时候直接将工费算入欠款中。

5.结算中心立即结算的单子也要显示实时欠款，欠料信息
功能已完成，请测试。

**Comment by mawenhao** [comment]
测试通过
