### ISSUE TITLE
山东库存初始化导入系统无数据但报条码重复

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#922]
问题：山东有如下条码导不进去
![qq 20161219162024](https://cloud.githubusercontent.com/assets/20296755/21305492/1442fb70-c607-11e6-891f-e61a126a822a.png)
原因：因为这几件货的条码前12位与库存中的条码重复，所以导致报“条码重复”的错
解决方法：把最后的原因告诉了山东客户，客户知道之后自己去验证了一下，发现确实存在
最后问题就解决了，客户回复如下：
![qq 20161219162517](https://cloud.githubusercontent.com/assets/20296755/21305626/c1aa3c9c-c607-11e6-933d-436976fd2472.png)

**Comment by hyh199111** [comment]
初始化报条码重复问题；
问题：找到问题所在的页面，报出缺少原大类。
原因：缺少配置文件。 
问题：条码重复。
原因：报错原因，条码重复。
![qq 20161220101440](https://cloud.githubusercontent.com/assets/24468189/21336063/ed4dfb5e-c69d-11e6-9d17-9d7d73d2fd27.png)
![Uploading QQ截图20161220101728.png…]()
