### ISSUE TITLE
进销存显示列问题

### ISSUE THREAD

**Issue by hyh199111** [kakazuo/yimengtech#936]
问题：明细进销存不能显示发货信息。
原因：js页面问题。
![qq 20161222113821](https://cloud.githubusercontent.com/assets/24468189/21416054/bc16d160-c84a-11e6-872e-7d3e3b850d19.png)
![qq 20161222132449](https://cloud.githubusercontent.com/assets/24468189/21416066/cd7e46cc-c84a-11e6-897d-1b825f3e1540.png)
![qq 20161222132540](https://cloud.githubusercontent.com/assets/24468189/21416071/d36806b8-c84a-11e6-9850-031a069b20bb.png)

**Comment by feixianhui** [comment]
测试通过
