### ISSUE TITLE
翡翠厂明细不打单据有一个结算单不对

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#939]
问题：28-999 湖南代销 的结算单的结算价和明细汇总出来的结算价有误差
原因：选择结算安倍率结算时没有减去误差
解决方法如下：
![qq 20161223141246](https://cloud.githubusercontent.com/assets/20296755/21448127/ea0a9a5a-c919-11e6-99f0-adf2e07807b1.png)

问题已解决，请测试！

**Comment by mawenhao** [comment]
测试通过
