### ISSUE TITLE
修改华洛芙旧品进销存问题

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#940]
需求：修改华洛芙客户提出的五个问题和研究是否能上缴之后不能退货
![qq 20161227114716](https://cloud.githubusercontent.com/assets/20296755/21491688/84cfd7e0-cc39-11e6-9e9b-a16545d599e7.png)
![qq 20161227114754](https://cloud.githubusercontent.com/assets/20296755/21491687/84c2ab10-cc39-11e6-9f9f-0957734533e6.png)
具体问题如下截图：
![qq 20161227114122](https://cloud.githubusercontent.com/assets/20296755/21489827/8682391c-cc29-11e6-9cbc-ea64c0688de4.png)
![qq 20161227114106](https://cloud.githubusercontent.com/assets/20296755/21489826/8682120c-cc29-11e6-96ae-7b5dbd9a025a.png)
![qq 20161227114053](https://cloud.githubusercontent.com/assets/20296755/21489828/8686db98-cc29-11e6-911a-781d217089fd.png)
![qq 20161227114042](https://cloud.githubusercontent.com/assets/20296755/21489830/868cb504-cc29-11e6-93f6-6949ce33c291.png)
![qq 20161227114029](https://cloud.githubusercontent.com/assets/20296755/21489829/868ab326-cc29-11e6-9895-979206a4e408.png)

**Comment by mawenhao** [comment]
测试通过
