### ISSUE TITLE
明细库存查询增加查询整个三级公司库存

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#942]
![qq 20161223155942](https://cloud.githubusercontent.com/assets/19886532/21449514/df5f6176-c928-11e6-9746-c04030402bb0.png)
增加查询三级公司库存选项。
增加公司参数 07310 全部三级公司勾选框  0-不启用  1-启用

**Comment by feixianhui** [comment]
测试通过

**Comment by feixianhui** [comment]
测试已通过
