### ISSUE TITLE
河南硬金一口价

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#964]
需求：由公司零售部结合部分商户意见提出硬金采用一口价计价方式，具体的计价办法为克重乘以设定好金价。在分秤商品时硬金成色商品按照已设定好硬金价格乘以克重。计算出的价格个位是5以下的变为5，价格是5以上的，变为0并向十位进位。

修改页面为：素金分秤页面
公司参数： 07311 硬金一口价 1 0-不启用, 1-启用
打印模板：6_1素金销售单   6_3调换销售单

修改内容：硬金在分秤是直接定好价 定价的方式为：克重乘以设定好金价（计算出的价格个位是5以下的变为5，价格是5以上的，变为0并向十位进位）。
硬金包括两种成色，分别为：硬金（成色id：19）和硬金999（成色id：4）.

功能已做好，请测试！

**Comment by feixianhui** [comment]
测试通过
