### ISSUE TITLE
重庆选择发货页面区分经代销

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#978]
同一单只能发同一性质类产品。
如：商品1为经销商品，则不能添加代销产品。
![000019](https://cloud.githubusercontent.com/assets/20236838/21705834/5998497e-d3fd-11e6-97ef-434044a60cc7.png)
有公司参数：07315  选择发货区分经代销，0：不区分，1：区分

**Comment by mawenhao** [comment]
测试通过
