### ISSUE TITLE
山东申请打印标签类型显示不正确

### ISSUE THREAD

**Issue by neverlosewy818** [kakazuo/yimengtech#981]
经排查，打印模板、js界面传的值均为正确的类别数据，问题出现在commonapi里面的
![qq 20170107092620](https://cloud.githubusercontent.com/assets/20236933/21738132/8431fefa-d4bb-11e6-8be9-4766e6d970f6.png)
sort1显示为父类，而非末级
与王超沟通过后发现这是华洛芙的需求（显示父类），但非其他地区的需求，故增加公司参数控制
![qq 20170107093245](https://cloud.githubusercontent.com/assets/20236933/21738306/b39e2176-d4bd-11e6-8563-433e397a6a4c.png)

公司参数  07316 类别按父类显示 0-允许，1-允许，不用就将参数删掉

**Comment by feixianhui** [comment]
测试通过
