### ISSUE TITLE
华洛芙的进出明细查询页面无法导出

### ISSUE THREAD

**Issue by superman6666** [kakazuo/yimengtech#984]
问题：华洛芙的进出明细查询页面无法导出
客户反应：
![qq 20170107091817](https://cloud.githubusercontent.com/assets/20296755/21738108/20c0deb8-d4bb-11e6-8c19-532ffcf9820a.png)

修改后的效果如下图：
![qq 20170107091438](https://cloud.githubusercontent.com/assets/20296755/21738121/6311da06-d4bb-11e6-92f5-cacd6e76b19b.png)

问题已解决，请测试！

**Comment by mawenhao** [comment]
测试通过
