### ISSUE TITLE
大丰零售收银0元异常

### ISSUE THREAD

**Issue by wangyubest** [kakazuo/yimengtech#991]
用户输入两件商品时，用旧料冲抵，舍位之后应收0元时，提示收银异常。
原因是：
![000020](https://cloud.githubusercontent.com/assets/20236838/21739561/d4f6bce6-d4d8-11e6-8517-b08c6e93e287.png)
被除数不能为0，加了一层判断，如果为0，rate变量直接赋值为0

**Comment by mawenhao** [comment]
测试通过
